/*
 * JExtendedTable.java
 *
 * Created on 14 May 2005, 02:53
 */

package chequeredflag.gui.beans;

import javax.swing.table.*;
import java.io.*;

/**
 *
 * @author  barrie
 */
public class JExtendedTable extends javax.swing.JTable implements Serializable
{ // Serializable had to be manually added and is a requirement for making use of beans.
    
    // To be an official bean, all variables must be supplied with getXXX and setXXX methods. 
    
    // Added to Netbeans by use of "Add to Palette..." option in the Tools menu. Selected class is then added by default.
    
    /** Creates new form BeanForm */
    public JExtendedTable() 
    {
        super(); // Possibly required for bean operation
        initComponents();
    }
    
    public TableCellRenderer getCellRenderer(int row, int column) 
    {
        Object dataValue = getValueAt(row,column);
        if (dataValue != null)
        {
            return getDefaultRenderer(dataValue.getClass());
        }
        return super.getCellRenderer(row,column);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
