/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * TrackGraphicalViewer.java
 *
 * Created on 24 March 2005, 01:27
 */

package chequeredflag.gui.track;

import chequeredflag.data.track.Track;
import chequeredflag.gui.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

/**
 *
 * @author  barrie
 */
public class TrackGraphicalViewer extends javax.swing.JInternalFrame {
	private static final int PAN_AMOUNT = 100;

	/** Creates new form graphicalEditorWindow */
    public TrackGraphicalViewer() {
        initComponents();
		initActions();
        m_trackPanel = new TrackPanel();
        getContentPane().add(m_trackPanel,  java.awt.BorderLayout.CENTER);
    }

    public void setTrack(Track track) {
        m_track = track;
        m_trackPanel.setTrack( track );
    }
    
    public void redrawTrackMap()
    {
    	// Passes on a signal to refresh the track map display
	
	m_trackPanel.redrawMap();
	
    }
    
    public void selectedSegment(int sectionType, int segmentNo)
    {
        // Passes on a signal to select a track map object
        
        m_trackPanel.selectSegment(sectionType, segmentNo);
    
    }
    

    private Track m_track;

    private TrackPanel m_trackPanel;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        bottomPanel = new javax.swing.JPanel();
        panLeftButton = new javax.swing.JButton();
        panRightButton = new javax.swing.JButton();
        panUpButton = new javax.swing.JButton();
        panDownButton = new javax.swing.JButton();
        zoomInButton = new javax.swing.JButton();
        zoomOutButton = new javax.swing.JButton();
        layoutModeButton = new javax.swing.JToggleButton();
        mapMenuBar = new javax.swing.JMenuBar();
        zoomMenu = new javax.swing.JMenu();
        zoomInItem = new javax.swing.JMenuItem();
        zoomOutItem = new javax.swing.JMenuItem();
        panMenu = new javax.swing.JMenu();
        panLeftItem = new javax.swing.JMenuItem();
        panRightItem = new javax.swing.JMenuItem();
        panUpItem = new javax.swing.JMenuItem();
        panDownItem = new javax.swing.JMenuItem();

        setTitle("Track Map");
        bottomPanel.setLayout(new java.awt.GridLayout(1, 6));

        panLeftButton.setText("Left");
        panLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panLeftButtonActionPerformed(evt);
            }
        });

        bottomPanel.add(panLeftButton);

        panRightButton.setText("Right");
        panRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panRightButtonActionPerformed(evt);
            }
        });

        bottomPanel.add(panRightButton);

        panUpButton.setText("Up");
        panUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panUpButtonActionPerformed(evt);
            }
        });

        bottomPanel.add(panUpButton);

        panDownButton.setText("Down");
        panDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panDownButtonActionPerformed(evt);
            }
        });

        bottomPanel.add(panDownButton);

        zoomInButton.setText("+");
        zoomInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInButtonActionPerformed(evt);
            }
        });

        bottomPanel.add(zoomInButton);

        zoomOutButton.setText("-");
        zoomOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutButtonActionPerformed(evt);
            }
        });

        bottomPanel.add(zoomOutButton);

        layoutModeButton.setText("Layout Mode");
        layoutModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleLayoutMode(evt);
            }
        });

        bottomPanel.add(layoutModeButton);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        zoomMenu.setText("Zoom");
        zoomInItem.setText("Zoom In");
        zoomInItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomIn(evt);
            }
        });

        zoomMenu.add(zoomInItem);

        zoomOutItem.setText("Zoom Out");
        zoomOutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOut(evt);
            }
        });

        zoomMenu.add(zoomOutItem);

        mapMenuBar.add(zoomMenu);

        panMenu.setText("Pan");
        panLeftItem.setText("Pan Left");
        panLeftItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panLeft(evt);
            }
        });

        panMenu.add(panLeftItem);

        panRightItem.setText("Pan Right");
        panRightItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panRight(evt);
            }
        });

        panMenu.add(panRightItem);

        panUpItem.setText("Pan Up");
        panUpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panUp(evt);
            }
        });

        panMenu.add(panUpItem);

        panDownItem.setText("Pan Down");
        panDownItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panDown(evt);
            }
        });

        panMenu.add(panDownItem);

        mapMenuBar.add(panMenu);

        setJMenuBar(mapMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleLayoutMode(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleLayoutMode

        // Toggles the layout mode used for the display of the track map
        
        boolean currentLayoutMode = false;
        if (m_track.getLayoutMode() == false)
        {
            currentLayoutMode = true;
        }
        m_track.setLayoutMode(currentLayoutMode);      
        redrawTrackMap();
        
    }//GEN-LAST:event_toggleLayoutMode

    private void zoomOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutButtonActionPerformed
        // Handler for zoom out button
        
        m_trackPanel.zoomOut();
        
        
    }//GEN-LAST:event_zoomOutButtonActionPerformed

    private void zoomInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInButtonActionPerformed
        // Handler for zoom in button
        
        m_trackPanel.zoomIn();
        
    }//GEN-LAST:event_zoomInButtonActionPerformed

    private void panDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panDownButtonActionPerformed
        // Handler for pan down button
        
        m_trackPanel.panY(-PAN_AMOUNT);
        
    }//GEN-LAST:event_panDownButtonActionPerformed

    private void panUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panUpButtonActionPerformed
        // Handler for pan up button
        
        m_trackPanel.panY(PAN_AMOUNT);
        
    }//GEN-LAST:event_panUpButtonActionPerformed

    private void panRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panRightButtonActionPerformed
        // Handler for pan right button
        
        m_trackPanel.panX(-PAN_AMOUNT);
        
    }//GEN-LAST:event_panRightButtonActionPerformed

    private void panLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panLeftButtonActionPerformed
        // Handler for pan left button
        
        m_trackPanel.panX(PAN_AMOUNT);
        
    }//GEN-LAST:event_panLeftButtonActionPerformed

    private void zoomIn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomIn
        // TODO add your handling code here:
    }//GEN-LAST:event_zoomIn

    private void zoomOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOut
        // TODO add your handling code here:
    }//GEN-LAST:event_zoomOut

    private void panLeft(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panLeft
        // TODO add your handling code here:
    }//GEN-LAST:event_panLeft

    private void panRight(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panRight
        // TODO add your handling code here:
    }//GEN-LAST:event_panRight

    private void panUp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panUp
        // TODO add your handling code here:
    }//GEN-LAST:event_panUp

    private void panDown(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panDown
        // TODO add your handling code here:
    }//GEN-LAST:event_panDown

	private void initActions() {
		initAction(new AbstractAction("Zoom In") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.zoomIn();
				}
			}, KeyEvent.VK_ADD, 0, zoomInItem);
		zoomMenu.add(zoomInItem);

		initAction(new AbstractAction("Zoom Out") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.zoomOut();
				}
			}, KeyEvent.VK_SUBTRACT, 0, zoomOutItem);
		zoomMenu.add(zoomOutItem);


		initAction(new AbstractAction("Pan Left") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panX(PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD4, 0, panLeftItem);
		panMenu.add(panLeftItem);

		initAction(new AbstractAction("Pan Right") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panX(-PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD6, 0, panRightItem);
		panMenu.add(panRightItem);

		initAction(new AbstractAction("Pan Up") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panY(PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD8, 0, panUpItem);
		panMenu.add(panUpItem);

		initAction(new AbstractAction("Pan Down") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panY(-PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD2, 0, panDownItem);
		panMenu.add(panDownItem);

		// diagonal panning actions (not in menu)
		initAction(new AbstractAction("Pan Down/Left") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(PAN_AMOUNT, -PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD1, 0, null);
		initAction(new AbstractAction("Pan Up/Left") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(PAN_AMOUNT, PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD7, 0, null);
		initAction(new AbstractAction("Pan Up/Right") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(-PAN_AMOUNT, PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD9, 0, null);
		initAction(new AbstractAction("Pan Down/Right") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(-PAN_AMOUNT, -PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD3, 0, null);

		// centering panning action (not in menu)
		initAction(new AbstractAction("Pan Center") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panCenter();
				}
			}, KeyEvent.VK_NUMPAD5, 0, null);
	}

	/**
	 * Binds an action to a key stroke and optionally to a menu.
	 * @param action
	 * @param keyCode
	 * @param modifiers
	 * @param menuItem may be null
	 */
	private void initAction(final Action action, final int keyCode, final int modifiers, final JMenuItem menuItem) 
        {
		final KeyStroke keyStroke = keyCode != 0 ? KeyStroke.getKeyStroke(keyCode, modifiers) : null;
		if (menuItem != null) 
                {
			menuItem.setAction(action);
                        if (keyStroke != null)
                            menuItem.setAccelerator(keyStroke);
		}
                else 
                {
			// manually set action and accelerator if not in menu
			getActionMap().put(action.getValue(Action.NAME), action);
			if (keyStroke != null)
				getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(
						keyStroke, action.getValue(Action.NAME));
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JToggleButton layoutModeButton;
    private javax.swing.JMenuBar mapMenuBar;
    private javax.swing.JButton panDownButton;
    private javax.swing.JMenuItem panDownItem;
    private javax.swing.JButton panLeftButton;
    private javax.swing.JMenuItem panLeftItem;
    private javax.swing.JMenu panMenu;
    private javax.swing.JButton panRightButton;
    private javax.swing.JMenuItem panRightItem;
    private javax.swing.JButton panUpButton;
    private javax.swing.JMenuItem panUpItem;
    private javax.swing.JButton zoomInButton;
    private javax.swing.JMenuItem zoomInItem;
    private javax.swing.JMenu zoomMenu;
    private javax.swing.JButton zoomOutButton;
    private javax.swing.JMenuItem zoomOutItem;
    // End of variables declaration//GEN-END:variables
    
}
