/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * TrackPanel.java
 *
 * Created on 30. März 2005, 23:13
 */

package chequeredflag.gui.track;

import chequeredflag.data.track.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.geom.AffineTransform;

/**
 *
 * @author  Klaus
 */
public class TrackPanel extends javax.swing.JPanel {

    static double ANGLE_SCALE_DEG = 360.0 / 65536;
    static double ANGLE_SCALE_RAD = 2 * Math.PI / 65536;

	private class TPMouseListener extends MouseAdapter implements MouseMotionListener, MouseWheelListener {
		private Point dragPoint;

		public void mouseDragged(MouseEvent e) {
			if (dragPoint != null) {
				if ((e.getModifiers() & (MouseEvent.SHIFT_MASK | MouseEvent.CTRL_MASK)) != 0) {
					if (e.isShiftDown())
						pan(e.getX() - dragPoint.x, e.getY() - dragPoint.y);
					else
						zoom(1.0 + (e.getY() - dragPoint.y + e.getX() - dragPoint.x) / 100.0);
					dragPoint = e.getPoint();
				} else
					dragPoint = null;
			}
		}

		public void mouseMoved(MouseEvent e) {
		}

		public void mousePressed(MouseEvent e) {
			if (e.getClickCount() == 1 && e.getButton() == MouseEvent.BUTTON1 &&
					(e.getModifiers() & (MouseEvent.SHIFT_MASK | MouseEvent.CTRL_MASK)) != 0)
				dragPoint = e.getPoint();
		}

		public void mouseReleased(MouseEvent e) {
			if (e.getButton() == MouseEvent.BUTTON1)
				dragPoint = null;
		}

		public void mouseWheelMoved(MouseWheelEvent e) {
			double dFactor;
			int nUnitsToScroll = e.getUnitsToScroll();
			if ( nUnitsToScroll > 0 ) {
				// zoom in
				dFactor = 1.1;
			} else {
				// zoom out
				dFactor = 0.9;
			}
			zoom( dFactor );
		}
	}

    /** Creates new form TrackPanel */
    public TrackPanel() {
        initComponents();
        standardTrans = new AffineTransform();
        standardTrans.setToIdentity();
        standardTrans.translate(100, 400);
        // Negative Y scale effectively changes Y direction (ascending
        // values from botton to top)
        standardTrans.scale( 1.0, -1.0 );
        // Scaling factor
        m_scale = 1.5;
        // First time drawing flag
        m_fFirstTime = true;
        // nothing selected up to now
        m_nSelectedTrackSegment = -1;
        m_nSelectedPitLaneSegment = -1;
        m_nSelectedCCLineSegment = -1;
        // Create mouse listener
        final TPMouseListener ml = new TPMouseListener();
        addMouseWheelListener(ml);
		addMouseListener(ml);
		addMouseMotionListener(ml);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    public void paintComponent( Graphics g )
    {
        if ( m_fPaintNew )
        {
            // new paint uses Seg structures (thus in-game-like calculations).
            // @@@ only for testing. not released yet!
            newPaintComponent( g );
        }

        else
        {
            Graphics2D g2d = (Graphics2D) g;
            Dimension d = getSize();

            // fill background
            Color oldColor = g2d.getColor();
            g2d.setColor(getBackground());
            g2d.fillRect(0, 0, d.width, d.height );
            g2d.setColor(oldColor);

            // On first drawing, adjust zooming and panning
            if ( m_fFirstTime )
            {
                m_fFirstTime = false;

                // set zooming and panning values so that track
                // appears in the middle of the window.
                Rectangle r = m_track.getBoundingRectangle();

                // Choose zoom factor so that a border of at least 10 percent
                // remains on each side of the track.
                double dScaleX = d.getWidth() / (r.getWidth() * 1.2);
                double dScaleY = d.getHeight() / (r.getHeight() * 1.2);
                if ( dScaleX > dScaleY )
                    m_scale = dScaleY;
                else
                    m_scale = dScaleX;

                // Center track in window
                standardTrans.setToIdentity();
                // Negative Y scale effectively changes Y direction (ascending
                // values from botton to top)
                standardTrans.scale( 1.0, -1.0 );
                standardTrans.translate( (d.getWidth() / 2.0) - m_scale * r.getCenterX(),
                                         -(d.getHeight() / 2.0) - m_scale * r.getCenterY() );
            }

            // change drawing direction to have positive y values going up.
            // Also panning could be done by the transformation, but not zooming
            // because automatic zoom looks bad.
            AffineTransform oldTrans = g2d.getTransform();
            g2d.transform( standardTrans );

            // draw all track segments
            TrackSegments trackSegments = m_track.getTrackSegments();
            TrackSegment trackSegment;
            m_fLeftFenceBridgedPrev = false;
            m_fRightFenceBridgedPrev = false;
            // Array for storing coordinates for display of "bridged" fence.
            // index 0: starting point of left bridged fence
            // index 1: end point of left bridged fence (up to current segment)
            // index 2/3: similar for right bridged fence.
            m_aXBridgePoints = new int[ 4 ];
            m_aYBridgePoints = new int[ 4 ];
            // Get initial fence distance from track header
            m_nLeftFenceDistPrev = m_track.getTrackDataHeader().getFenceDistL();
            m_nRightFenceDistPrev = m_track.getTrackDataHeader().getFenceDistL();

            for ( int i = 1; i <= trackSegments.size(); i++ )
            {
                trackSegment = trackSegments.getAt( i );

                // Adjust settings for selected/unselected segments
                if ( i == m_nSelectedTrackSegment )
                {
                    // Paint selected segment in orange
                    g2d.setColor(Color.orange);
                }
                else
                {
                    // Other segments are painted in black
                    g2d.setColor(Color.black);
                }

                if ( trackSegment.getCurvature() == 0 )
                {
                    // Straight
                    // Draw track segment itself.
                    int aXPoints[] = new int[ 4 ];
                    int aYPoints[] = new int[ 4 ];
                    // Width unit is 1/1024 of TLU.
                    double dXDiff = Math.cos( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
                    double dYDiff = Math.sin( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
                    aXPoints[ 0 ] = new Double((trackSegment.getPosXStart() - dXDiff) * m_scale).intValue();
                    aYPoints[ 0 ] = new Double((trackSegment.getPosYStart() + dYDiff) * m_scale).intValue();
                    aXPoints[ 1 ] = new Double((trackSegment.getPosXStart() + dXDiff) * m_scale).intValue();
                    aYPoints[ 1 ] = new Double((trackSegment.getPosYStart() - dYDiff) * m_scale).intValue();

                    dXDiff = Math.cos( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
                    dYDiff = Math.sin( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
                    aXPoints[ 2 ] = new Double((trackSegment.getPosXEnd() + dXDiff) * m_scale).intValue();
                    aYPoints[ 2 ] = new Double((trackSegment.getPosYEnd() - dYDiff) * m_scale).intValue();
                    aXPoints[ 3 ] = new Double((trackSegment.getPosXEnd() - dXDiff) * m_scale).intValue();
                    aYPoints[ 3 ] = new Double((trackSegment.getPosYEnd() + dYDiff) * m_scale).intValue();
                    g2d.drawPolygon( aXPoints, aYPoints, 4 );
                } // Straight
                else
                {
                    // Curve
                    double dOuterRadiusStart = ( trackSegment.getRadius() + ((double)trackSegment.getWidthStart()) / 1024.0 ) * m_scale;
                    double dInnerRadiusStart = ( trackSegment.getRadius() - ((double)trackSegment.getWidthStart()) / 1024.0 ) * m_scale;
                    double dOuterRadiusEnd   = ( trackSegment.getRadius() + ((double)trackSegment.getWidthEnd()) / 1024.0 ) * m_scale;
                    double dInnerRadiusEnd   = ( trackSegment.getRadius() - ((double)trackSegment.getWidthEnd()) / 1024.0 ) * m_scale;
                    double dStAngle  = Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD;
                    double dEndAngle = Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD;
                    int    nCenterX  = new Double( trackSegment.getPosXCenter() * m_scale ).intValue();
                    int    nCenterY  = new Double( trackSegment.getPosYCenter() * m_scale ).intValue();
                    if ( trackSegment.getCurvature() > 0 )
                    {
                        // right turn
                        // outer line
                        drawArc(g2d, nCenterX, nCenterY,
                                dStAngle, dEndAngle,
                                dOuterRadiusStart, dOuterRadiusEnd);
                        // inner line
                        drawArc(g2d, nCenterX, nCenterY,
                                dStAngle, dEndAngle,
                                dInnerRadiusStart, dInnerRadiusEnd);
                        // separation line at start of segment
                        g2d.drawLine( nCenterX + new Double( dOuterRadiusStart * Math.cos( dStAngle )).intValue(),
                                      nCenterY - new Double( dOuterRadiusStart * Math.sin( dStAngle )).intValue(),
                                      nCenterX + new Double( dInnerRadiusStart * Math.cos( dStAngle )).intValue(),
                                      nCenterY - new Double( dInnerRadiusStart * Math.sin( dStAngle )).intValue());
                    }
                    else
                    {
                        // left turn: give start/end angle in opposite order
                        drawArc(g2d, nCenterX, nCenterY,
                                dEndAngle, dStAngle,
                                dOuterRadiusStart, dOuterRadiusEnd );
                        // inner line
                        drawArc(g2d, nCenterX, nCenterY,
                                dEndAngle, dStAngle,
                                dInnerRadiusStart, dInnerRadiusEnd );
                        // separation line at start of segment
                        g2d.drawLine( nCenterX + new Double( dOuterRadiusStart * Math.cos( dStAngle )).intValue(),
                                      nCenterY - new Double( dOuterRadiusStart * Math.sin( dStAngle )).intValue(),
                                      nCenterX + new Double( dInnerRadiusStart * Math.cos( dStAngle )).intValue(),
                                      nCenterY - new Double( dInnerRadiusStart * Math.sin( dStAngle )).intValue());
                    }
                } // curve

                // Paint kerbs
                paintKerbs(trackSegment, g2d);

                // Paint fence
                paintFence(trackSegment, g2d);
            }

            // draw all pit lane segments
            // reset fence data.
            m_fLeftFenceBridgedPrev = false;
            m_fRightFenceBridgedPrev = false;
            // Pit lane uses same fence distance as track???
            m_nLeftFenceDistPrev = m_track.getTrackDataHeader().getFenceDistL();
            m_nRightFenceDistPrev = m_track.getTrackDataHeader().getFenceDistL();

            oldColor = g2d.getColor();
            trackSegments = m_track.getPitlaneSegments();
            for ( int i = 1; i <= trackSegments.size(); i++ )
            {
                trackSegment = trackSegments.getAt( i );

                if ( i == m_nSelectedPitLaneSegment )
                {
                    // Paint selected segment pink
                    g2d.setColor(Color.pink);
                }
                else
                {
                    // Default pit lane segment is blue
                    g2d.setColor(Color.blue);
                }

                if ( trackSegment.getCurvature() == 0 )
                {
                    // Straight
                    int aXPoints[] = new int[ 4 ];
                    int aYPoints[] = new int[ 4 ];
                    // Width unit is 1/1024 of TLU.
                    double dXDiff = Math.cos( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
                    double dYDiff = Math.sin( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
                    aXPoints[ 0 ] = new Double((trackSegment.getPosXStart() - dXDiff) * m_scale).intValue();
                    aYPoints[ 0 ] = new Double((trackSegment.getPosYStart() + dYDiff) * m_scale).intValue();
                    aXPoints[ 1 ] = new Double((trackSegment.getPosXStart() + dXDiff) * m_scale).intValue();
                    aYPoints[ 1 ] = new Double((trackSegment.getPosYStart() - dYDiff) * m_scale).intValue();

                    dXDiff = Math.cos( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
                    dYDiff = Math.sin( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
                    aXPoints[ 2 ] = new Double((trackSegment.getPosXEnd() + dXDiff) * m_scale).intValue();
                    aYPoints[ 2 ] = new Double((trackSegment.getPosYEnd() - dYDiff) * m_scale).intValue();
                    aXPoints[ 3 ] = new Double((trackSegment.getPosXEnd() - dXDiff) * m_scale).intValue();
                    aYPoints[ 3 ] = new Double((trackSegment.getPosYEnd() + dYDiff) * m_scale).intValue();
                    g2d.drawPolygon( aXPoints, aYPoints, 4 );
                }
                else
                {
                    // Curve
                    if ( trackSegment.getCurvature() > 0 )
                    {
                        // right turn
                        // outer line
                        drawArc(g2d,
                                new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                                new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                                Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                                Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                                ( trackSegment.getRadius() + ((double)trackSegment.getWidthStart()) / 1024.0 ) * m_scale,
                                ( trackSegment.getRadius() + ((double)trackSegment.getWidthEnd()) / 1024.0 ) * m_scale );
                        // inner line
                        drawArc(g2d,
                                new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                                new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                                Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                                Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                                ( trackSegment.getRadius() - ((double)trackSegment.getWidthStart()) / 1024.0 ) * m_scale,
                                ( trackSegment.getRadius() - ((double)trackSegment.getWidthEnd()) / 1024.0 ) * m_scale );
                    }
                    else
                    {
                        // left turn: give start/end angle in opposite order
                        drawArc(g2d,
                                new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                                new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                                Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                                Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                                ( trackSegment.getRadius() + ((double)trackSegment.getWidthStart()) / 1024.0 ) * m_scale,
                                ( trackSegment.getRadius() + ((double)trackSegment.getWidthEnd()) / 1024.0 ) * m_scale );
                        // inner line
                        drawArc(g2d,
                                new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                                new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                                Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                                Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                                ( trackSegment.getRadius() - ((double)trackSegment.getWidthStart()) / 1024.0 ) * m_scale,
                                ( trackSegment.getRadius() - ((double)trackSegment.getWidthEnd()) / 1024.0 ) * m_scale );
                    }
                }

                // Paint kerbs
                paintKerbs( trackSegment, g2d );

                // Paint fence
                paintFence( trackSegment, g2d );
            }
            g2d.setColor(oldColor);

            // display the computer car line
            paintCCLine( m_track.getCCLine(), g2d );

            // reset transformations
            g2d.setTransform( oldTrans );
        }
    }

    /**
        New method for painting track panel is using the data structures
        similar to in-game calculations.
    */

    protected void newPaintComponent( Graphics g )
    {
        Graphics2D g2d = (Graphics2D) g;
        Dimension d = getSize();

        // fill background
        Color oldColor = g2d.getColor();
        g2d.setColor(getBackground());
        g2d.fillRect(0, 0, d.width, d.height );
        g2d.setColor(oldColor);

        // On first drawing, adjust zooming and panning
        if ( m_fFirstTime )
        {
            m_fFirstTime = false;

            // set zooming and panning values so that track
            // appears in the middle of the window.
            Rectangle r = m_track.getF1GPBoundingRectangle();

            // Choose zoom factor so that a border of at least 10 percent
            // remains on each side of the track.
            double dScaleX = d.getWidth() / (r.getWidth() * 1.2);
            double dScaleY = d.getHeight() / (r.getHeight() * 1.2);
            if ( dScaleX > dScaleY )
                m_scale = dScaleY;
            else
                m_scale = dScaleX;

            // Center track in window
            standardTrans.setToIdentity();
            // Negative Y scale effectively changes Y direction (ascending
            // values from botton to top)
            standardTrans.scale( 1.0, -1.0 );
            standardTrans.translate( (d.getWidth() / 2.0) - m_scale * r.getCenterX(),
                                     -(d.getHeight() / 2.0) - m_scale * r.getCenterY() );
        }

        // change drawing direction to have positive y values going up.
        // Also panning could be done by the transformation, but not zooming
        // because automatic zoom looks bad.
        AffineTransform oldTrans = g2d.getTransform();
        g2d.transform( standardTrans );

        // draw all track segments
        TrackSegments trackSegments = m_track.getTrackSegments();
        Seg seg, segNext;
        m_fLeftFenceBridgedPrev = false;
        m_fRightFenceBridgedPrev = false;
        // Array for storing coordinates for display of "bridged" fence.
        // index 0: starting point of left bridged fence
        // index 1: end point of left bridged fence (up to current segment)
        // index 2/3: similar for right bridged fence.
        m_aXBridgePoints = new int[ 4 ];
        m_aYBridgePoints = new int[ 4 ];
        // Get initial fence distance from track header
        m_nLeftFenceDistPrev = m_track.getTrackDataHeader().getFenceDistL();
        m_nRightFenceDistPrev = m_track.getTrackDataHeader().getFenceDistL();

        for ( int i = 0; i <= trackSegments.getMaxTrackSegIndex() - 1; i++ )
        {
            // Adjust settings for selected/unselected segments
            // m_nSelectedTrackSegment is WHOLE segment, not only single Seg @@@
            if ( i == m_nSelectedTrackSegment )
            {
                // Paint selected segment in orange
                g2d.setColor(Color.orange);
            }
            else
            {
                // Other segments are painted in black
                g2d.setColor(Color.black);
            }

            // draw a simple rectangle (polygon) in any case.
            // Each Seg is only one tlu.
            int aXPoints[] = new int[ 4 ];
            int aYPoints[] = new int[ 4 ];
            seg = trackSegments.getSegAt( i );
            segNext = trackSegments.getSegAt( i + 1 );
            double dXDiff = Math.cos( seg.getAngleZ() * ANGLE_SCALE_RAD ) * seg.getTrackWidth();
            double dYDiff = Math.sin( seg.getAngleZ() * ANGLE_SCALE_RAD ) * seg.getTrackWidth();
            aXPoints[ 0 ] = new Double(((double)seg.getPosX() + dXDiff) * m_scale).intValue();
            aYPoints[ 0 ] = new Double(((double)seg.getPosY() - dYDiff) * m_scale).intValue();
            aXPoints[ 1 ] = new Double(((double)segNext.getPosX() + dXDiff) * m_scale).intValue();
            aYPoints[ 1 ] = new Double(((double)segNext.getPosY() - dYDiff) * m_scale).intValue();
            aXPoints[ 2 ] = new Double(((double)segNext.getPosX() - dXDiff) * m_scale).intValue();
            aYPoints[ 2 ] = new Double(((double)segNext.getPosY() + dYDiff) * m_scale).intValue();
            aXPoints[ 3 ] = new Double(((double)seg.getPosX() - dXDiff) * m_scale).intValue();
            aYPoints[ 3 ] = new Double(((double)seg.getPosY() + dYDiff) * m_scale).intValue();
            g2d.drawPolygon( aXPoints, aYPoints, 4 );

            // Draw CCLine
            dXDiff = Math.cos( seg.getAngleZ() * ANGLE_SCALE_RAD ) * seg.getCCLine();
            dYDiff = Math.sin( seg.getAngleZ() * ANGLE_SCALE_RAD ) * seg.getCCLine();
            aXPoints[ 0 ] = new Double(((double)seg.getPosX() + dXDiff) * m_scale).intValue();
            aYPoints[ 0 ] = new Double(((double)seg.getPosY() - dYDiff) * m_scale).intValue();
            dXDiff = Math.cos( seg.getAngleZ() * ANGLE_SCALE_RAD ) * segNext.getCCLine();
            dYDiff = Math.sin( seg.getAngleZ() * ANGLE_SCALE_RAD ) * segNext.getCCLine();
            aXPoints[ 1 ] = new Double(((double)segNext.getPosX() + dXDiff) * m_scale).intValue();
            aYPoints[ 1 ] = new Double(((double)segNext.getPosY() - dYDiff) * m_scale).intValue();
            g2d.setColor(Color.red);
            g2d.drawLine(aXPoints[ 0 ], aYPoints[ 0 ], aXPoints[ 1 ], aYPoints[ 1 ] );
        }

        // reset transformations
        g2d.setTransform( oldTrans );
    }

    /**
      Draw an arc with center (x,y), starting angle dStAngle, end angle dEndAngle, start radius dStRadius
      and end radius dEndRadius.
      Used to draw all curved lines.
      To be able to draw 'circles' with varying radius, a large number of short straights is drawn.
      Zooming/Panning appears outside of this method.
    */

    private void drawArc( Graphics2D g2d, int x, int y, double dStAngle, double dEndAngle,
                     double dStRadius, double dEndRadius)
    {
        double r, a;
        int nPosXStart, nPosYStart, nPosX, nPosY;

        // EndAngle has to be within 2 * PI of StAngle, else a full circle
        // will be drawn.
        while ( dEndAngle - dStAngle > Math.PI * 2 )
            dEndAngle -= Math.PI * 2;

        // radius change per angle unit (radiens)
        a = (dEndRadius - dStRadius)/(dEndAngle - dStAngle);

        // Draw a number of straight lines along the circle.
        // Each line should have a length of about 10 pixels.
        // First, find out which angle increment gives a length of 10 pixels.
        double dAngleIncrement;
        if ( Math.abs(dStRadius) > 50 )
            // calculate increment to get lines about 10 pixels long
            dAngleIncrement = Math.abs( 2 * Math.asin( 5.0 / dStRadius ) );
        else
            // small circle: divide full circle into 32 sectors
            dAngleIncrement = 2 * Math.PI / 32;

        // calculate starting point
        nPosXStart = x + new Double( dStRadius * Math.cos(dStAngle)).intValue();
        nPosYStart = y - new Double( dStRadius * Math.sin(dStAngle)).intValue();

        // draw a number of short lines
        double dAngle = dStAngle + dAngleIncrement;
        while ( dAngle < dEndAngle )
        {
            // calculate radius for current angle
            r = dStRadius + (dAngle - dStAngle) * a;

            // calculate point on circle for this angle
            nPosX = x + new Double( r * Math.cos(dAngle)).intValue();
            nPosY = y - new Double( r * Math.sin(dAngle)).intValue();
            
            // draw line to this point
            g2d.drawLine( nPosXStart, nPosYStart, nPosX, nPosY );

            // proceed to next increment.
            dAngle = dAngle + dAngleIncrement;
            nPosXStart = nPosX;
            nPosYStart = nPosY;
        }

        // draw a last short line to the end point of rhe arc
        nPosX = x + new Double( dEndRadius * Math.cos(dEndAngle)).intValue();
        nPosY = y - new Double( dEndRadius * Math.sin(dEndAngle)).intValue();
        g2d.drawLine( nPosXStart, nPosYStart, nPosX, nPosY );
    }

    private Track m_track;
    private AffineTransform standardTrans;
    private double m_scale;
    private boolean m_fFirstTime;
    private boolean m_fPaintNew = true;

    public void setTrack(Track track) {
        m_track = track;
        m_fFirstTime = true; // trigger calculations on first drawing
    }

    public void zoomIn() {
        zoom( 1.5 );
    }

    public void zoomOut() {
        zoom( 2.0 / 3.0 );
    }

    protected void zoom(double dFactor)
    {
        Dimension d = getSize();
        double dTransX, dTransY;
        dTransX = standardTrans.getTranslateX();
        dTransY = standardTrans.getTranslateY();

        m_scale = m_scale * dFactor;

        dTransX = dTransX * dFactor + (1 - dFactor) * d.width / 2;
        dTransY = dTransY * dFactor + (1 - dFactor) * d.height / 2;

        standardTrans.setToIdentity();
        // Negative Y scale effectively changes Y direction (ascending
        // values from botton to top)
        standardTrans.scale( 1.0, -1.0 );
        standardTrans.translate( dTransX, -dTransY );
        repaint();
    }

    public void panX( int nXPan ) {
        standardTrans.translate( nXPan, 0 );
	repaint();
    }

    public void panY( int nYPan ) {
        standardTrans.translate( 0, -nYPan );
	repaint();
    }
    
    /** repaints the track map display */
    public void redrawMap()
    {
        // first recalculate the layout
        m_track.calculateTrackLayout();
        m_track.calculateCCLine();

        // then repaint
        repaint();
    }
    
    /**
        sectionType: 1 - Track, 2 - Pit, 3 - CCLine
        segmentNo: 1-based number of the segment (-1 if nothing is selected).
    */
    public void selectSegment(int sectionType, int segmentNo)
    {
        // Selects a given segment depending on the tree node selected by the user
        switch ( sectionType )
        {
        case 1: // Track segment selection
            m_nSelectedTrackSegment = segmentNo;
            break;
        case 2: // Pit lane segment selection
            m_nSelectedPitLaneSegment = segmentNo;
            break;
        case 3: // CCLine segment selection
            m_nSelectedCCLineSegment = segmentNo;
            break;
        default:
            // invalid section type
            break;
        }
        repaint();
    }

    public void pan(int x, int y) {
        standardTrans.translate(x, -y);
        repaint();
    }

    public void panCenter() {
        moveTo(getWidth() / 2, -getHeight() / 2);
    }

    public void moveTo(int x, int y) {
        // Set coordinate to be the point in the bottom left corner.
        // Calculate new translation matrix.
        standardTrans.setToIdentity();
        // Negative Y scale effectively changes Y direction (ascending
        // values from botton to top)
        standardTrans.scale( 1.0, -1.0 );
        standardTrans.translate( x, y);
        // repaint with new settings
        repaint();
    }

    protected void paintFence(final TrackSegment trackSegment, Graphics2D g2d) {
        boolean fLeftFence, fRightFence, fLeftFenceBridged, fRightFenceBridged;
        double dXDiffFence, dYDiffFence;
        double dXDiff, dYDiff;
        int nFenceStartX, nFenceStartY;

        // Check if fences are present
        fLeftFenceBridged = (trackSegment.getFlags() & 0x20) != 0;
        fLeftFence = !fLeftFenceBridged && ((trackSegment.getFlags() & 0x2000) == 0);
        fRightFenceBridged = (trackSegment.getFlags() & 0x10) != 0;
        fRightFence = !fRightFenceBridged && ((trackSegment.getFlags() & 0x1000) == 0);

        // calculate x/y differences from track width based on which the fence
        // distance will be calculated. @@@ different track width at start and end of segment possible!
        dXDiff = Math.cos( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
        dYDiff = Math.sin( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;

        // calculate fence distance from middle of the road.
        double dFenceDistStart, dFenceDistEnd;

        // set drawing colour for fences
        Color nonFenceColor;
        nonFenceColor = g2d.getColor();
        g2d.setColor(Color.cyan);

        if ( fLeftFence )
        {
            // Any bridged fence left for drawing?
            if ( m_fLeftFenceBridgedPrev )
            {
                // Bridging ends here
                g2d.drawLine( m_aXBridgePoints[ 0 ],
                              m_aYBridgePoints[ 0 ],
                              m_aXBridgePoints[ 1 ],
                              m_aYBridgePoints[ 1 ]);
                // clear bridge flag
                m_fLeftFenceBridgedPrev = false;
            }

            if ( trackSegment.getCurvature() == 0 )
            {
                // Straight track segment
                // Fence distance is measured in 1/32s of the track width, so to get
                // to the point where the fence is, multiply the X/YDiff by (1 + 1/32 FenceDist).
                dXDiffFence = dXDiff * ( 1.0 + ((double)m_nLeftFenceDistPrev) / 32.0);
                dYDiffFence = dYDiff * ( 1.0 + ((double)m_nLeftFenceDistPrev) / 32.0);
                nFenceStartX = new Double((trackSegment.getPosXStart() + dXDiffFence) * m_scale).intValue();
                nFenceStartY = new Double((trackSegment.getPosYStart() - dYDiffFence) * m_scale).intValue();
                dXDiffFence = dXDiff * ( 1.0 + ((double)trackSegment.getFenceDistL()) / 32.0);
                dYDiffFence = dYDiff * ( 1.0 + ((double)trackSegment.getFenceDistL()) / 32.0);;
                g2d.drawLine(nFenceStartX,
                             nFenceStartY,
                             new Double((trackSegment.getPosXEnd() + dXDiffFence) * m_scale).intValue(),
                             new Double((trackSegment.getPosYEnd() - dYDiffFence) * m_scale).intValue());
            }
            else
            {
                // curve
                dFenceDistStart = ( (double)trackSegment.getWidthStart() / 1024.0 ) * ( 1.0 + ((double)m_nLeftFenceDistPrev) / 32.0);
                dFenceDistEnd   = ( (double)trackSegment.getWidthEnd() / 1024.0 ) * ( 1.0 + ((double)trackSegment.getFenceDistL()) / 32.0);
                if ( trackSegment.getCurvature() > 0 )
                {
                    // right turn
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            ( trackSegment.getRadius() + dFenceDistStart ) * m_scale,
                            ( trackSegment.getRadius() + dFenceDistEnd ) * m_scale );
                }
                else
                {
                    // left turn: give start/end angle in opposite order.
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            // Note: negative radius, this add fence dist!
                            ( trackSegment.getRadius() + dFenceDistEnd ) * m_scale,
                            ( trackSegment.getRadius() + dFenceDistStart ) * m_scale );
                }
            }
        };

        if ( fRightFence )
        {
            // Any bridged fence left for drawing?
            if ( m_fRightFenceBridgedPrev )
            {
                g2d.drawLine( m_aXBridgePoints[ 2 ],
                              m_aYBridgePoints[ 2 ],
                              m_aXBridgePoints[ 3 ],
                              m_aYBridgePoints[ 3 ]);
                // clear bridge flag
                m_fRightFenceBridgedPrev = false;
            }

            if ( trackSegment.getCurvature() == 0 )
            {
                dXDiffFence = dXDiff * ( 1.0 + ((double)m_nRightFenceDistPrev) / 32.0);
                dYDiffFence = dYDiff * ( 1.0 + ((double)m_nRightFenceDistPrev) / 32.0);
                nFenceStartX = new Double((trackSegment.getPosXStart() - dXDiffFence) * m_scale).intValue();
                nFenceStartY = new Double((trackSegment.getPosYStart() + dYDiffFence) * m_scale).intValue();
                dXDiffFence = dXDiff * ( 1.0 + ((double)trackSegment.getFenceDistR()) / 32.0);
                dYDiffFence = dYDiff * ( 1.0 + ((double)trackSegment.getFenceDistR()) / 32.0);;
                g2d.drawLine(nFenceStartX,
                             nFenceStartY,
                             new Double((trackSegment.getPosXEnd() - dXDiffFence) * m_scale).intValue(),
                             new Double((trackSegment.getPosYEnd() + dYDiffFence) * m_scale).intValue());
            } // straight segment
            else
            {
                // curve
                dFenceDistStart = ( (double)trackSegment.getWidthStart() / 1024.0 ) * ( 1.0 + ((double)m_nRightFenceDistPrev) / 32.0);
                dFenceDistEnd   = ( (double)trackSegment.getWidthEnd() / 1024.0 ) * ( 1.0 + ((double)trackSegment.getFenceDistR()) / 32.0);
                if ( trackSegment.getCurvature() > 0 )
                {
                    // right turn
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            ( trackSegment.getRadius() - dFenceDistStart ) * m_scale,
                            ( trackSegment.getRadius() - dFenceDistEnd ) * m_scale );
                }
                else
                {
                    // left turn: give start/end angle in opposite order.
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            // Note: negative radius, thus subtract fence dist!
                            ( trackSegment.getRadius() - dFenceDistEnd ) * m_scale,
                            ( trackSegment.getRadius() - dFenceDistStart ) * m_scale );
                }
            }
        }; 
        g2d.setColor( nonFenceColor );

        // Check bridging and calculate coordinates for later drawing.
        if ( fLeftFenceBridged )
        {
            if ( !m_fLeftFenceBridgedPrev )
            {
                // calculate starting point of bridged fence and store in array
                dXDiffFence = dXDiff * ( 1.0 + ((double)m_nLeftFenceDistPrev) / 32.0);
                dYDiffFence = dYDiff * ( 1.0 + ((double)m_nLeftFenceDistPrev) / 32.0);
                m_aXBridgePoints[ 0 ] = new Double((trackSegment.getPosXStart() + dXDiffFence) * m_scale).intValue();
                m_aYBridgePoints[ 0 ] = new Double((trackSegment.getPosYStart() - dYDiffFence) * m_scale).intValue();
                // set flag that starting point was found
                m_fLeftFenceBridgedPrev = true;
            }
            // Always store end point into array. Will be overwritten when next segment
            // is also "bridged"
            dXDiffFence = dXDiff * ( 1.0 + ((double)trackSegment.getFenceDistL()) / 32.0);
            dYDiffFence = dYDiff * ( 1.0 + ((double)trackSegment.getFenceDistL()) / 32.0);;
            m_aXBridgePoints[ 1 ] = new Double((trackSegment.getPosXEnd() + dXDiffFence) * m_scale).intValue();
            m_aYBridgePoints[ 1 ] = new Double((trackSegment.getPosYEnd() - dYDiffFence) * m_scale).intValue();
        };
        if ( fRightFenceBridged )
        {
            if ( !m_fRightFenceBridgedPrev )
            {
                // calculate starting point of bridged fence and store in array
                dXDiffFence = dXDiff * ( 1.0 + ((double)m_nRightFenceDistPrev) / 32.0);
                dYDiffFence = dYDiff * ( 1.0 + ((double)m_nRightFenceDistPrev) / 32.0);
                m_aXBridgePoints[ 2 ] = new Double((trackSegment.getPosXStart() - dXDiffFence) * m_scale).intValue();
                m_aYBridgePoints[ 2 ] = new Double((trackSegment.getPosYStart() + dYDiffFence) * m_scale).intValue();
                // set flag that starting point was found
                m_fRightFenceBridgedPrev = true;
            }
            // Always store end point into array. Will be overwritten when next segment
            // is also "bridged"
            dXDiffFence = dXDiff * ( 1.0 + ((double)trackSegment.getFenceDistR()) / 32.0);
            dYDiffFence = dYDiff * ( 1.0 + ((double)trackSegment.getFenceDistR()) / 32.0);;
            m_aXBridgePoints[ 3 ] = new Double((trackSegment.getPosXEnd() - dXDiffFence) * m_scale).intValue();
            m_aYBridgePoints[ 3 ] = new Double((trackSegment.getPosYEnd() + dYDiffFence) * m_scale).intValue();
        };

        // store fence distance for next segment
        m_nLeftFenceDistPrev = trackSegment.getFenceDistL();
        m_nRightFenceDistPrev = trackSegment.getFenceDistR();
    } // paintFence

    // When kerbs are present, a green line is painted just outside the track itself.
    // Distance between track and green line is 1/4 of half track width (i.e. the
    // distance between track middle and border).
    protected void paintKerbs(final TrackSegment trackSegment, Graphics2D g2d)
    {
        // set drawing colour for kerbs
        Color colorOld;
        colorOld = g2d.getColor();
        g2d.setColor(Color.green);

        // Width unit is 1/1024 of TLU.
        double dXDiffStart = Math.cos( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
        double dYDiffStart = Math.sin( Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
        double dXDiffEnd   = Math.cos( Math.PI - trackSegment.getAngleEnd()   * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
        double dYDiffEnd   = Math.sin( Math.PI - trackSegment.getAngleEnd()   * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;

        if ((trackSegment.getFlags() & 0x800) != 0 )
        {
            // Left kerbs are present
            if ( trackSegment.getCurvature() == 0 )
            {
                // straight
                int aXPoints[] = new int[ 4 ];
                int aYPoints[] = new int[ 4 ];
                aXPoints[ 0 ] = new Double((trackSegment.getPosXStart() + dXDiffStart) * m_scale).intValue();
                aYPoints[ 0 ] = new Double((trackSegment.getPosYStart() - dYDiffStart) * m_scale).intValue();
                aXPoints[ 1 ] = new Double((trackSegment.getPosXStart() + ( dXDiffStart * 1.25 ) ) * m_scale).intValue();
                aYPoints[ 1 ] = new Double((trackSegment.getPosYStart() - ( dYDiffStart * 1.25 ) ) * m_scale).intValue();

                aXPoints[ 2 ] = new Double((trackSegment.getPosXEnd() + ( dXDiffEnd * 1.25 ) ) * m_scale).intValue();
                aYPoints[ 2 ] = new Double((trackSegment.getPosYEnd() - ( dYDiffEnd * 1.25 ) ) * m_scale).intValue();
                aXPoints[ 3 ] = new Double((trackSegment.getPosXEnd() + dXDiffEnd) * m_scale).intValue();
                aYPoints[ 3 ] = new Double((trackSegment.getPosYEnd() - dYDiffEnd) * m_scale).intValue();
                g2d.drawPolygon( aXPoints, aYPoints, 4 );
            }
            else
            {
                // curved segment
                if ( trackSegment.getCurvature() > 0 )
                {
                    // right turn
                    // kerbs are on outer side
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            ( trackSegment.getRadius() + ( 1.25 * (((double)trackSegment.getWidthStart()) / 1024.0 ))) * m_scale,
                            ( trackSegment.getRadius() + ( 1.25 * (((double)trackSegment.getWidthEnd()) / 1024.0 ))) * m_scale );
                }
                else
                {
                    // left turn: give start/end angle in opposite order
                    // kerbs are on inner side
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            // Note: in this case, radius is negative
                            ( trackSegment.getRadius() + ( 1.25 * (((double)trackSegment.getWidthEnd()) / 1024.0 ))) * m_scale,
                            ( trackSegment.getRadius() + ( 1.25 * (((double)trackSegment.getWidthStart()) / 1024.0 ))) * m_scale );
                }
                // short straight pieces to connect to track edge.
                g2d.drawLine( new Double( ( trackSegment.getPosXStart() + dXDiffStart ) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYStart() - dYDiffStart ) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosXStart() + 1.25 * dXDiffStart ) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYStart() - 1.25 * dYDiffStart ) * m_scale ).intValue() );
                g2d.drawLine( new Double( ( trackSegment.getPosXEnd() + dXDiffEnd) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYEnd() - dYDiffEnd) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosXEnd() + 1.25 * dXDiffEnd) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYEnd() - 1.25 * dYDiffEnd) * m_scale ).intValue() );
            }
        }

        if ((trackSegment.getFlags() & 0x400) != 0 )
        {
            // Right kerbs are present
            if ( trackSegment.getCurvature() == 0 )
            {
                // straight
                // straight
                int aXPoints[] = new int[ 4 ];
                int aYPoints[] = new int[ 4 ];
                aXPoints[ 0 ] = new Double((trackSegment.getPosXStart() - dXDiffStart) * m_scale).intValue();
                aYPoints[ 0 ] = new Double((trackSegment.getPosYStart() + dYDiffStart) * m_scale).intValue();
                aXPoints[ 1 ] = new Double((trackSegment.getPosXStart() - ( dXDiffStart * 1.25 ) ) * m_scale).intValue();
                aYPoints[ 1 ] = new Double((trackSegment.getPosYStart() + ( dYDiffStart * 1.25 ) ) * m_scale).intValue();

                aXPoints[ 2 ] = new Double((trackSegment.getPosXEnd() - ( dXDiffEnd * 1.25 ) ) * m_scale).intValue();
                aYPoints[ 2 ] = new Double((trackSegment.getPosYEnd() + ( dYDiffEnd * 1.25 ) ) * m_scale).intValue();
                aXPoints[ 3 ] = new Double((trackSegment.getPosXEnd() - dXDiffEnd) * m_scale).intValue();
                aYPoints[ 3 ] = new Double((trackSegment.getPosYEnd() + dYDiffEnd) * m_scale).intValue();
                g2d.drawPolygon( aXPoints, aYPoints, 4 );
            }
            else
            {
                // curved segment
                if ( trackSegment.getCurvature() > 0 )
                {
                    // right turn
                    // kerbs are on inner side
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            ( trackSegment.getRadius() - ( 1.25 * (((double)trackSegment.getWidthStart()) / 1024.0 ))) * m_scale,
                            ( trackSegment.getRadius() - ( 1.25 * (((double)trackSegment.getWidthEnd()) / 1024.0 ))) * m_scale );
                    // short straight pieces to connect to track edge.
                    // @@@ missing
                }
                else
                {
                    // left turn: give start/end angle in opposite order
                    // kerbs are on inner side
                    drawArc(g2d,
                            new Double( trackSegment.getPosXCenter() * m_scale ).intValue(),
                            new Double( trackSegment.getPosYCenter() * m_scale ).intValue(),
                            Math.PI - trackSegment.getAngleEnd() * ANGLE_SCALE_RAD,
                            Math.PI - trackSegment.getAngleStart() * ANGLE_SCALE_RAD,
                            // Note: in this case, radius is negative
                            ( trackSegment.getRadius() - ( 1.25 * (((double)trackSegment.getWidthEnd()) / 1024.0 ))) * m_scale,
                            ( trackSegment.getRadius() - ( 1.25 * (((double)trackSegment.getWidthStart()) / 1024.0 ))) * m_scale );
                }
                // short straight pieces to connect to track edge.
                g2d.drawLine( new Double( ( trackSegment.getPosXStart() - dXDiffStart ) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYStart() + dYDiffStart ) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosXStart() - 1.25 * dXDiffStart ) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYStart() + 1.25 * dYDiffStart ) * m_scale ).intValue() );
                g2d.drawLine( new Double( ( trackSegment.getPosXEnd() - dXDiffEnd) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYEnd() + dYDiffEnd) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosXEnd() - 1.25 * dXDiffEnd) * m_scale ).intValue(),
                              new Double( ( trackSegment.getPosYEnd() + 1.25 * dYDiffEnd) * m_scale ).intValue() );
            }
        }

        // reset to old drawing color
        g2d.setColor( colorOld );
    } // paintKerbs

    private int m_nLeftFenceDistPrev;

    private int m_nRightFenceDistPrev;

    private int [] m_aXBridgePoints;

    private int [] m_aYBridgePoints;

    private boolean m_fLeftFenceBridgedPrev;

    private boolean m_fRightFenceBridgedPrev;

    // Segment number for selection
    private int m_nSelectedTrackSegment;
    private int m_nSelectedPitLaneSegment;
    private int m_nSelectedCCLineSegment;

    // Display the computer car line.
    protected void paintCCLine(CCLine ccLine, Graphics2D g2d) {
        CCLineSegment ccLineSegment;
        Color oldColor = g2d.getColor();
        for ( int i = 1; i <= ccLine.size(); i++ )
        {
            ccLineSegment = ccLine.getAt( i );

            if ( i == m_nSelectedCCLineSegment )
            {
                // paint selected segment in magenta
                g2d.setColor(Color.MAGENTA);
            }
            else
            {
                // default color is red.
                g2d.setColor(Color.RED);
            }

            // straight or curved?
            if ( ccLineSegment.isStraight() )
            {
                // straight
                g2d.drawLine( new Double( ( ccLineSegment.getPosXStart() ) * m_scale ).intValue(),
                              new Double( ( ccLineSegment.getPosYStart() ) * m_scale ).intValue(),
                              new Double( ( ccLineSegment.getPosXEnd() ) * m_scale ).intValue(),
                              new Double( ( ccLineSegment.getPosYEnd() ) * m_scale ).intValue() );                
            }
            else
            {
                // if this segment carries a shift value, draw shift segment as connection line.
                if ( ccLineSegment.getShift() > 0 )
                {
                    CCLineSegment segShift = ccLineSegment.getShiftSegment();
                    // use different color for shift segment so shifting is visible
                    // in track display.
                    Color colorSegment = g2d.getColor();
                    g2d.setColor( Color.GREEN );
                    g2d.drawLine( new Double( segShift.getPosXStart() * m_scale ).intValue(),
                                  new Double( segShift.getPosYStart() * m_scale ).intValue(),
                                  new Double( segShift.getPosXEnd() * m_scale ).intValue(),
                                  new Double( segShift.getPosYEnd() * m_scale ).intValue() );
                    g2d.setColor( colorSegment );
                }

                if ( ccLineSegment.turnsRight() )
                {
                    // right turn
                    drawArc(g2d,
                            new Double( ( ccLineSegment.getPosXCenter() ) * m_scale ).intValue(),
                            new Double( ( ccLineSegment.getPosYCenter() ) * m_scale ).intValue(),
                            Math.PI - ccLineSegment.getAngleStart(),
                            Math.PI - ccLineSegment.getAngleEnd(),
                            ccLineSegment.getRadius() * m_scale,
                            ccLineSegment.getRadius() * m_scale );
                }
                else
                {
                    // left turn: change order of angles
                    drawArc(g2d,
                            new Double( ( ccLineSegment.getPosXCenter() ) * m_scale ).intValue(),
                            new Double( ( ccLineSegment.getPosYCenter() ) * m_scale ).intValue(),
                            Math.PI - ccLineSegment.getAngleEnd(),
                            Math.PI - ccLineSegment.getAngleStart(),
                            ccLineSegment.getRadius() * m_scale,
                            ccLineSegment.getRadius() * m_scale );
                }
            } // curved segment
        }
        // reset painting color of context
        g2d.setColor( oldColor );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
