/*
 * MainGUI.java
 *
 * Created on 22 February 2005, 22:28
 */

package Chequeredflag;

/**
 *
 * @author  barrie
 */
public class MainGUI extends javax.swing.JFrame 
{
    
    /** Creates new form MainGUI */
    public MainGUI() 
    {
        super("Chequered Flag - An open-source F1GP/WC editor");
        initComponents();
        setVisible(true);
        setSize(576,432);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainToolBar = new javax.swing.JToolBar();
        mainMenuBar = new javax.swing.JMenuBar();
        mainMenu1 = new javax.swing.JMenu();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(mainToolBar);

        mainMenu1.setText("Menu");
        mainMenuBar.add(mainMenu1);

        setJMenuBar(mainMenuBar);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mainMenu1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JToolBar mainToolBar;
    // End of variables declaration//GEN-END:variables
    
}
