/*
 * MainGUI.java
 *
 * Created on 22 February 2005, 22:28
 */

package Chequeredflag;

import javax.swing.*;

/**
 *
 * @author  barrie
 */
public class MainGUI extends javax.swing.JFrame 
{
    
    /** Creates new form MainGUI */
    public MainGUI() 
    {
        // Setting main frame information
        super("Chequered Flag - An open-source F1GP/WC editor");
        initComponents();
        setSize(576,432);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        titlePanel = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        descText = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        trackButton = new javax.swing.JButton();
        gameButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        titlePanel.setLayout(new java.awt.GridLayout(2, 1));

        mainTitle.setFont(new java.awt.Font("Dialog", 1, 48));
        mainTitle.setForeground(new java.awt.Color(255, 0, 51));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setText("Chequered Flag");
        mainTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(mainTitle);

        descText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descText.setText("A general purpose F1GP/WC editor");
        descText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(descText);

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.GridLayout(2, 2));

        trackButton.setText("Open Track Editor");
        trackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTrackEditor(evt);
            }
        });

        buttonPanel.add(trackButton);

        gameButton.setText("Open Game Editor");
        buttonPanel.add(gameButton);

        aboutButton.setText("About Chequered Flag");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAbout(evt);
            }
        });

        buttonPanel.add(aboutButton);

        exitButton.setText("Exit Chequered Flag");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgram(evt);
            }
        });

        buttonPanel.add(exitButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void exitProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgram
        // Immediately exits the program with no further steps
        
        System.exit(0);
    }//GEN-LAST:event_exitProgram

    private void displayAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAbout
        // Creates and opens the About dialog
        
        AboutGUI aboutDialog = new AboutGUI();
        
    }//GEN-LAST:event_displayAbout

    private void openTrackEditor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTrackEditor
        // Creates and opens the track editor frame
        
        TrackGUI trackEditorDisplay = new TrackGUI();
        
    }//GEN-LAST:event_openTrackEditor
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel descText;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gameButton;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton trackButton;
    // End of variables declaration//GEN-END:variables
    
}
