/*
 * TrackGUI.java
 *
 * Created on 22 February 2005, 22:28
 */

package Chequeredflag;

import javax.swing.*;

/**
 *
 * @author  barrie
 */
public class TrackGUI extends javax.swing.JFrame 
{
    
    /** Creates new form TrackGUI */
    public TrackGUI() 
    {
        // Setting main frame information
        super("Chequered Flag - An open-source F1GP/WC editor");
        initComponents();
        setSize(576,432);
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openTrack = new javax.swing.JMenuItem();
        saveTrack = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JSeparator();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        openTrack.setText("Open F1GP/WC Track");
        fileMenu.add(openTrack);

        saveTrack.setText("Save F1GP/WC Track");
        fileMenu.add(saveTrack);

        fileMenu.add(menuSeparator1);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgram(evt);
            }
        });

        fileMenu.add(exitItem);

        mainMenuBar.add(fileMenu);

        helpMenu.setText("Help");
        aboutItem.setText("About");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAbout(evt);
            }
        });

        helpMenu.add(aboutItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }//GEN-END:initComponents

    private void displayAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAbout
        // Displays the About dialog
        
        AboutGUI aboutDialog = new AboutGUI();
                
    }//GEN-LAST:event_displayAbout

    private void exitProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgram
        // Immediately exits the program with no further steps
        
        System.exit(0);
        
    }//GEN-LAST:event_exitProgram

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new TrackGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JSeparator menuSeparator1;
    private javax.swing.JMenuItem openTrack;
    private javax.swing.JMenuItem saveTrack;
    // End of variables declaration//GEN-END:variables
    
}
