/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * AboutGUI.java
 *
 * Created on 01 October 2006, 00:50
 */

package chequeredflag.gui;

/**
 *
 * @author  barrie
 */
public class AboutGUI extends javax.swing.JInternalFrame {
    
    /** Creates new form AboutGUI */
    public AboutGUI() 
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        titleText = new javax.swing.JLabel();
        descText = new javax.swing.JLabel();
        f1gpText = new javax.swing.JLabel();
        byText = new javax.swing.JLabel();
        versionText = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        setPreferredSize(new java.awt.Dimension(433, 289));
        titleText.setFont(new java.awt.Font("Dialog", 1, 36));
        titleText.setForeground(new java.awt.Color(255, 51, 51));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("Chequered Flag");
        getContentPane().add(titleText);

        descText.setForeground(new java.awt.Color(51, 51, 255));
        descText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descText.setText("A general purpose open-source editor for");
        getContentPane().add(descText);

        f1gpText.setFont(new java.awt.Font("Dialog", 1, 18));
        f1gpText.setForeground(new java.awt.Color(255, 51, 51));
        f1gpText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1gpText.setText("Formula One Grand Prix / World Circuit");
        getContentPane().add(f1gpText);

        byText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        byText.setText("Development by Klaus Six, Barrie Millar and Rene Smit");
        getContentPane().add(byText);

        versionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionText.setText("Version 0.1.1");
        getContentPane().add(versionText);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        getContentPane().add(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Closes the about form
        
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
        
    }//GEN-LAST:event_okButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel byText;
    private javax.swing.JLabel descText;
    private javax.swing.JLabel f1gpText;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel versionText;
    // End of variables declaration//GEN-END:variables
    
}
