/*
 * AboutGUI.java
 *
 * Created on 01 October 2006, 00:50
 */

package chequeredflag.gui;

/**
 *
 * @author  barrie
 */
public class AboutGUI extends javax.swing.JInternalFrame {
    
    /** Creates new form AboutGUI */
    public AboutGUI() 
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        titleText = new javax.swing.JLabel();
        descText = new javax.swing.JLabel();
        f1gpText = new javax.swing.JLabel();
        byText = new javax.swing.JLabel();
        versionText = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(6, 1));

        titleText.setFont(new java.awt.Font("Dialog", 1, 36));
        titleText.setForeground(new java.awt.Color(255, 51, 51));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("Chequered Flag");
        getContentPane().add(titleText);

        descText.setForeground(new java.awt.Color(51, 51, 255));
        descText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descText.setText("A general purpose open-source editor for");
        getContentPane().add(descText);

        f1gpText.setFont(new java.awt.Font("Dialog", 1, 18));
        f1gpText.setForeground(new java.awt.Color(255, 51, 51));
        f1gpText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f1gpText.setText("Formula One Grand Prix / World Circuit");
        getContentPane().add(f1gpText);

        byText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        byText.setText("Development by Klaus Six, Barrie Millar and Rene Smit");
        getContentPane().add(byText);

        versionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionText.setText("Version 0.1.0");
        getContentPane().add(versionText);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        getContentPane().add(okButton);

        pack();
    }//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Closes the about form
        
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
        
    }//GEN-LAST:event_okButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel byText;
    private javax.swing.JLabel descText;
    private javax.swing.JLabel f1gpText;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel versionText;
    // End of variables declaration//GEN-END:variables
    
}
