/*
 * FileDialog.java
 *
 * Created on 18 March 2005, 22:44
 */

package chequeredflag.gui;

/**
 *
 * @author  barrie
 */
public class FileDialog extends javax.swing.JDialog {
    
    /** Creates new form FileDialog */
    public FileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public String showOpenDialog()
    {
        fileChooser.setFileFilter(new TrackFilter());
        int userChoice = fileChooser.showOpenDialog(this);
        String fileName = fileChooser.getSelectedFile().getPath();
        return fileName;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fileChooser.setFileFilter(fileChooser.getFileFilter());
        fileChooser.setFileView(fileChooser.getFileView());
        getContentPane().add(fileChooser, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
    
}
