/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * FileDialog.java
 *
 * Created on 18 March 2005, 22:44
 */

package chequeredflag.gui;

import chequeredflag.gui.executable.ExecutableFilter;
import chequeredflag.gui.track.TrackFilter;
import java.io.File;

/**
 *
 * @author  barrie
 */
public class FileDialog extends javax.swing.JDialog {
    
    /** Creates new form FileDialog */
    public FileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setFilterType(int filterType)
    {
        // Sets the type of file filter used
        // 1 - Track Filter
        // 2 - Executable Filter
        
        switch(filterType)
        {
            case 1: fileChooser.setFileFilter(new TrackFilter()); break;
            case 2: fileChooser.setFileFilter(new ExecutableFilter()); break;
        }
        
    }
    
    public void setInitialDirectory(String directoryName)
    {
        fileChooser.setCurrentDirectory(new File(directoryName));
    }
    
    public String showOpenDialog()
    {
        // Displays an input dialog for opening F1GP tracks
        
        int userChoice = fileChooser.showOpenDialog(this);
        String fileName = fileChooser.getSelectedFile().getPath();
        return fileName;
    }
    
    public String showSaveDialog()
    {
        // Displays a save dialog for storing F1GP tracks
        
        int userChoice = fileChooser.showSaveDialog(this);
        String fileName = fileChooser.getSelectedFile().getPath();
        return fileName;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        fileChooser.setFileFilter(fileChooser.getFileFilter());
        fileChooser.setFileView(fileChooser.getFileView());
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        getContentPane().add(fileChooser, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileChooserActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
    
}
