/*
 * GraphicalEditorWindow.java
 *
 * Created on 24 March 2005, 01:27
 */

package chequeredflag.gui;

import chequeredflag.data.track.*;

/**
 *
 * @author  barrie
 */
public class GraphicalEditorWindow extends javax.swing.JInternalFrame {
    
    /** Creates new form graphicalEditorWindow */
    public GraphicalEditorWindow() {
        initComponents();
        m_trackPanel = new TrackPanel();
        getContentPane().add(m_trackPanel,  java.awt.BorderLayout.CENTER);
    }

    public void setTrack(Track track) {
        m_track = track;
        m_trackPanel.setTrack( track );
    }

    private Track m_track;

    private TrackPanel m_trackPanel;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mapMenuBar = new javax.swing.JMenuBar();
        zoomMenu = new javax.swing.JMenu();
        zoomInItem = new javax.swing.JMenuItem();
        zoomOutItem = new javax.swing.JMenuItem();
        panMenu = new javax.swing.JMenu();
        panLeftItem = new javax.swing.JMenuItem();
        panRightItem = new javax.swing.JMenuItem();
        panUpItem = new javax.swing.JMenuItem();
        panDownItem = new javax.swing.JMenuItem();

        setTitle("Track Map");
        zoomMenu.setText("Zoom");
        zoomInItem.setText("Zoom In");
        zoomInItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomIn(evt);
            }
        });

        zoomMenu.add(zoomInItem);

        zoomOutItem.setText("Zoom Out");
        zoomOutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOut(evt);
            }
        });

        zoomMenu.add(zoomOutItem);

        mapMenuBar.add(zoomMenu);

        panMenu.setText("Pan");
        panLeftItem.setText("Pan left");
        panLeftItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panLeft(evt);
            }
        });

        panMenu.add(panLeftItem);

        panRightItem.setText("Pan right");
        panRightItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panRight(evt);
            }
        });

        panMenu.add(panRightItem);

        panUpItem.setText("Pan up");
        panUpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panUp(evt);
            }
        });

        panMenu.add(panUpItem);

        panDownItem.setText("Pan down");
        panDownItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panDown(evt);
            }
        });

        panMenu.add(panDownItem);

        mapMenuBar.add(panMenu);

        setJMenuBar(mapMenuBar);

        pack();
    }//GEN-END:initComponents

private void panDown(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panDown
    m_trackPanel.panY( -100 );
}//GEN-LAST:event_panDown

private void panUp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panUp
    m_trackPanel.panY( 100 );
}//GEN-LAST:event_panUp

private void panRight(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panRight
    m_trackPanel.panX( 100 );
}//GEN-LAST:event_panRight

private void panLeft(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panLeft
    m_trackPanel.panX( -100 );
}//GEN-LAST:event_panLeft

    private void zoomOut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOut
        // Make use of the mapZoomOut function
        
        mapZoomOut();
        
    }//GEN-LAST:event_zoomOut

    private void zoomIn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomIn
        // Make use of the mapZoomIn function
        
        mapZoomIn();
        
    }//GEN-LAST:event_zoomIn
    
    private void mapZoomIn()
    {
        // Method to zoom in from a track map. May be used from several locations (menu, toolbar, etc)
    
        m_trackPanel.zoomIn(); 
    }
    
    private void mapZoomOut()
    {
        // Method to zoom out from a track map. May be used from several locations (menu, toolbar, etc)
        
        m_trackPanel.zoomOut();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mapMenuBar;
    private javax.swing.JMenuItem panDownItem;
    private javax.swing.JMenuItem panLeftItem;
    private javax.swing.JMenu panMenu;
    private javax.swing.JMenuItem panRightItem;
    private javax.swing.JMenuItem panUpItem;
    private javax.swing.JMenuItem zoomInItem;
    private javax.swing.JMenu zoomMenu;
    private javax.swing.JMenuItem zoomOutItem;
    // End of variables declaration//GEN-END:variables
    
}
