/*
 * GraphicalEditorWindow.java
 *
 * Created on 24 March 2005, 01:27
 */

package chequeredflag.gui;

import chequeredflag.data.track.Track;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

/**
 *
 * @author  barrie
 */
public class GraphicalEditorWindow extends javax.swing.JInternalFrame {
	private static final int PAN_AMOUNT = 100;

	/** Creates new form graphicalEditorWindow */
    public GraphicalEditorWindow() {
        initComponents();
		initActions();
        m_trackPanel = new TrackPanel();
        getContentPane().add(m_trackPanel,  java.awt.BorderLayout.CENTER);
    }

    public void setTrack(Track track) {
        m_track = track;
        m_trackPanel.setTrack( track );
    }
    
    public void redrawTrackMap()
    {
    	// Passes on a signal to refresh the track map display
	
	m_trackPanel.redrawMap();
	
    }

    private Track m_track;

    private TrackPanel m_trackPanel;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mapMenuBar = new javax.swing.JMenuBar();
        zoomMenu = new javax.swing.JMenu();
        zoomInItem = new javax.swing.JMenuItem();
        zoomOutItem = new javax.swing.JMenuItem();
        panMenu = new javax.swing.JMenu();
        panLeftItem = new javax.swing.JMenuItem();
        panRightItem = new javax.swing.JMenuItem();
        panUpItem = new javax.swing.JMenuItem();
        panDownItem = new javax.swing.JMenuItem();

        setTitle("Track Map");
		zoomMenu.setText("Zoom");
		panMenu.setText("Pan");
		mapMenuBar.add(zoomMenu);
		mapMenuBar.add(panMenu);
        setJMenuBar(mapMenuBar);

        pack();
    }//GEN-END:initComponents

	private void initActions() {
		initAction(new AbstractAction("Zoom In") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.zoomIn();
				}
			}, KeyEvent.VK_ADD, 0, zoomInItem);
		zoomMenu.add(zoomInItem);

		initAction(new AbstractAction("Zoom Out") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.zoomOut();
				}
			}, KeyEvent.VK_SUBTRACT, 0, zoomOutItem);
		zoomMenu.add(zoomOutItem);


		initAction(new AbstractAction("Pan Left") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panX(PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD4, 0, panLeftItem);
		panMenu.add(panLeftItem);

		initAction(new AbstractAction("Pan Right") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panX(-PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD6, 0, panRightItem);
		panMenu.add(panRightItem);

		initAction(new AbstractAction("Pan Up") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panY(PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD8, 0, panUpItem);
		panMenu.add(panUpItem);

		initAction(new AbstractAction("Pan Down") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panY(-PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD2, 0, panDownItem);
		panMenu.add(panDownItem);

		// diagonal panning actions (not in menu)
		initAction(new AbstractAction("Pan Down/Left") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(PAN_AMOUNT, -PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD1, 0, null);
		initAction(new AbstractAction("Pan Up/Left") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(PAN_AMOUNT, PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD7, 0, null);
		initAction(new AbstractAction("Pan Up/Right") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(-PAN_AMOUNT, PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD9, 0, null);
		initAction(new AbstractAction("Pan Down/Right") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.pan(-PAN_AMOUNT, -PAN_AMOUNT);
				}
			}, KeyEvent.VK_NUMPAD3, 0, null);

		// centering panning action (not in menu)
		initAction(new AbstractAction("Pan Center") {
				public void actionPerformed(final ActionEvent e) {
					m_trackPanel.panCenter();
				}
			}, KeyEvent.VK_NUMPAD5, 0, null);
	}

	/**
	 * Binds an action to a key stroke and optionally to a menu.
	 * @param action
	 * @param keyCode
	 * @param modifiers
	 * @param menuItem may be null
	 */
	private void initAction(final Action action, final int keyCode, final int modifiers, final JMenuItem menuItem) {
		final KeyStroke keyStroke = keyCode != 0 ? KeyStroke.getKeyStroke(keyCode, modifiers) : null;
		if (menuItem != null) {
			menuItem.setAction(action);
			if (keyStroke != null)
				menuItem.setAccelerator(keyStroke);
		} else {
			// manually set action and accelerator if not in menu
			getActionMap().put(action.getValue(Action.NAME), action);
			if (keyStroke != null)
				getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(
						keyStroke, action.getValue(Action.NAME));
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mapMenuBar;
    private javax.swing.JMenuItem panDownItem;
    private javax.swing.JMenuItem panLeftItem;
    private javax.swing.JMenu panMenu;
    private javax.swing.JMenuItem panRightItem;
    private javax.swing.JMenuItem panUpItem;
    private javax.swing.JMenuItem zoomInItem;
    private javax.swing.JMenu zoomMenu;
    private javax.swing.JMenuItem zoomOutItem;
    // End of variables declaration//GEN-END:variables
    
}
