/*
 * GraphicalEditorWindow.java
 *
 * Created on 24 March 2005, 01:27
 */

package chequeredflag.gui;

import chequeredflag.data.track.*;

/**
 *
 * @author  barrie
 */
public class GraphicalEditorWindow extends javax.swing.JInternalFrame {
    
    /** Creates new form graphicalEditorWindow */
    public GraphicalEditorWindow() {
        initComponents();
        m_trackPanel = new TrackPanel();
        getContentPane().add(m_trackPanel,  java.awt.BorderLayout.CENTER);
    }

    public void setTrack(Track track) {
        m_track = track;
        m_trackPanel.setTrack( track );
    }

    private Track m_track;

    private TrackPanel m_trackPanel;

    public void zoomIn() {
        m_trackPanel.zoomIn();
    }

    public void zoomOut() {
        m_trackPanel.zoomOut();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
