/*
 * MainGUI.java
 *
 * Created on 22 February 2005, 22:28
 */

package chequeredflag.gui;

import javax.swing.*;
import java.io.*;
import chequeredflag.data.track.*;

/**
 *
 * @author  barrie
 */
public class MainGUI extends javax.swing.JFrame 
{
    
    private Track currentTrack;
            
    /** Creates new form MainGUI */
    public MainGUI() 
    {
        // Setting main frame information
        // The first three commands should appear in this order before any other.
        super("Chequered Flag - An open-source F1GP/WC editor");
        initComponents();
        
        // WARNING: Very little internal window management being done at present
        
        setContentPane(mainEditorWindow);
        
        // Start of normal commands
        
        setSize(576,432);
        setVisible(true);
        
               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainEditorWindow = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenu();
        openTrack = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JSeparator();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResizeEvent(evt);
            }
        });

        getContentPane().add(mainEditorWindow);

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        openMenu.setText("Open...");
        openTrack.setText("Track File");
        openTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTrackFile(evt);
            }
        });

        openMenu.add(openTrack);

        fileMenu.add(openMenu);

        fileMenu.add(menuSeparator1);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgram(evt);
            }
        });

        fileMenu.add(exitItem);

        mainMenuBar.add(fileMenu);

        helpMenu.setText("Help");
        aboutItem.setText("About");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });

        helpMenu.add(aboutItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }//GEN-END:initComponents

    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        // Displays the About dialog
        
        AboutGUI aboutWindow = new AboutGUI();
        aboutWindow.setVisible(true);
        aboutWindow.setTitle("About Chequered Flag");
        mainEditorWindow.add(aboutWindow);
        aboutWindow.toFront();
        try
        {
            aboutWindow.setSelected(true);
        }
        catch (Exception exceptionError)
        {
            exceptionError.printStackTrace();
        }
    }//GEN-LAST:event_aboutItemActionPerformed

    private void windowResizeEvent(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResizeEvent
        // Detects any change in the size of the main editor window and adjusts internal frames accordingly
        
        // WARNING: Will need to be implemented
        
    }//GEN-LAST:event_windowResizeEvent
     
    private void openTrackFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTrackFile
        // Opens a new track file and reads in data by using ksix's track input processing
        
        FileDialog fileDialog = new FileDialog(this,true);  
        String fileName = fileDialog.showOpenDialog();
        File trackFile = new File(fileName);
        currentTrack = new Track();
        currentTrack.load(trackFile);
        
        // Calculate size of track editing window
        
        int windowX = mainEditorWindow.getWidth();
        int windowY = mainEditorWindow.getHeight();
        TrackWindow newTrackWindow = new TrackWindow(currentTrack, fileName, this);
        newTrackWindow.reshape(0,0,windowX,windowY);
        newTrackWindow.setVisible(true);
        
        // Add track editor window
        
        mainEditorWindow.add(newTrackWindow);
                           
    }//GEN-LAST:event_openTrackFile
   
    private void exitProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgram
        // Immediately exits the program with no further steps
        
        System.exit(0);
        
    }//GEN-LAST:event_exitProgram

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane mainEditorWindow;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JSeparator menuSeparator1;
    private javax.swing.JMenu openMenu;
    private javax.swing.JMenuItem openTrack;
    // End of variables declaration//GEN-END:variables
    
}
