/*
 * MainGUI.java
 *
 * Created on 22 February 2005, 22:28
 */

package chequeredflag.gui;

import javax.swing.*;
import java.io.*;
import chequeredflag.data.track.*;
import chequeredflag.data.gui.*;
import java.util.prefs.Preferences;
import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import java.awt.event.WindowEvent;

/**
 *
 * @author  barrie
 */
public class MainGUI extends javax.swing.JFrame implements WindowListener
{
    
    private Track currentTrack;
    private boolean closingProgram;
            
    /** Creates new form MainGUI */
    public MainGUI() 
    {
        // Setting main frame information
        // The first three commands should appear in this order before any other.
        super("Chequered Flag - An open-source F1GP/WC editor");
        initComponents();
        
        // Setting global variables
        
        closingProgram = false;
        
        // Perform window management
        
        setContentPane(mainEditorWindow);
        addWindowListener(this);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        // Start of normal commands
        
        setSize(576,432);
        setVisible(true);
        
        // Setting menu item visibility based on recent file availability
        
        updateRecentFileList(new String());
                      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainEditorWindow = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenu();
        openTrack = new javax.swing.JMenuItem();
        menuSeparator3 = new javax.swing.JSeparator();
        optionsMenu = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JSeparator();
        lastFileMenuOne = new javax.swing.JMenuItem();
        lastFileMenuTwo = new javax.swing.JMenuItem();
        lastFileMenuThree = new javax.swing.JMenuItem();
        lastFileMenuFour = new javax.swing.JMenuItem();
        menuSeparator2 = new javax.swing.JSeparator();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResizeEvent(evt);
            }
        });

        getContentPane().add(mainEditorWindow);

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        openMenu.setText("Open...");
        openTrack.setText("Track File");
        openTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTrack(evt);
            }
        });

        openMenu.add(openTrack);

        fileMenu.add(openMenu);

        fileMenu.add(menuSeparator3);

        optionsMenu.setText("Options");
        optionsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsMenuActionPerformed(evt);
            }
        });

        fileMenu.add(optionsMenu);

        fileMenu.add(menuSeparator1);

        lastFileMenuOne.setText("Item");
        lastFileMenuOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFileMenuOneActionPerformed(evt);
            }
        });

        fileMenu.add(lastFileMenuOne);

        lastFileMenuTwo.setText("Item");
        lastFileMenuTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFileMenuTwoActionPerformed(evt);
            }
        });

        fileMenu.add(lastFileMenuTwo);

        lastFileMenuThree.setText("Item");
        lastFileMenuThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFileMenuThreeActionPerformed(evt);
            }
        });

        fileMenu.add(lastFileMenuThree);

        lastFileMenuFour.setText("Item");
        lastFileMenuFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastFileMenuFourActionPerformed(evt);
            }
        });

        fileMenu.add(lastFileMenuFour);

        fileMenu.add(menuSeparator2);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgram(evt);
            }
        });

        fileMenu.add(exitItem);

        mainMenuBar.add(fileMenu);

        helpMenu.setText("Help");
        aboutItem.setText("About");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutItemActionPerformed(evt);
            }
        });

        helpMenu.add(aboutItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }//GEN-END:initComponents

    public void windowClosing(WindowEvent wetEvent)
    {
        // Handles window closing event
                
        quitChequeredFlag();
    }
	
    public void windowOpened(WindowEvent wetEvent) 
    {
    }
	
    public void windowClosed(WindowEvent wetEvent)
    {
    }
	
    public void windowIconified(WindowEvent wetEvent)
    {
    }
	
    public void windowDeiconified(WindowEvent wetEvent)
    {
    }
	
    public void windowActivated(WindowEvent wetEvent)
    {
    }
	
    public void windowDeactivated(WindowEvent wetEvent)
    {
    }
    
    
    private void optionsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsMenuActionPerformed
        // Handles the event after the option menu item is activated by the user.
        
        OptionsWindow programOptions = new OptionsWindow(this);
        programOptions.setVisible(true);
        programOptions.setTitle("Chequered Flag Options");
        mainEditorWindow.add(programOptions);
        programOptions.toFront();
        try
        {
            programOptions.setSelected(true);
        }
        catch (Exception exceptionError)
        {
            exceptionError.printStackTrace();
        }
                
    }//GEN-LAST:event_optionsMenuActionPerformed

    private void lastFileMenuFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFileMenuFourActionPerformed
        // Handler method for recent file selection four
        
        recentFileMenuHandler(3);
        
    }//GEN-LAST:event_lastFileMenuFourActionPerformed

    private void lastFileMenuThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFileMenuThreeActionPerformed
        // Handler method for recent file selection three
        
        recentFileMenuHandler(2);
        
    }//GEN-LAST:event_lastFileMenuThreeActionPerformed

    private void lastFileMenuTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFileMenuTwoActionPerformed
        // Handler method for recent file selection two
        
        recentFileMenuHandler(1);
        
    }//GEN-LAST:event_lastFileMenuTwoActionPerformed

    private void lastFileMenuOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastFileMenuOneActionPerformed
        // Handler method for recent file selection one        
        
        recentFileMenuHandler(0);
        
    }//GEN-LAST:event_lastFileMenuOneActionPerformed

    public void recentFileMenuHandler(int buttonIndex)
    {
        RecentFiles usedFiles = new RecentFiles();
        String recentFilePath = usedFiles.getRecentFilePath(buttonIndex);
        openTrackFile(recentFilePath);
    }
    
    private void aboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutItemActionPerformed
        // Displays the About dialog
        
        AboutGUI aboutWindow = new AboutGUI();
        aboutWindow.setVisible(true);
        aboutWindow.setTitle("About Chequered Flag");
        mainEditorWindow.add(aboutWindow);
        aboutWindow.toFront();
        try
        {
            aboutWindow.setSelected(true);
        }
        catch (Exception exceptionError)
        {
            exceptionError.printStackTrace();
        }
    }//GEN-LAST:event_aboutItemActionPerformed

    private void windowResizeEvent(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResizeEvent
        // Detects any change in the size of the main editor window and adjusts internal frames accordingly
        
        // WARNING: Will need to be implemented
        
    }//GEN-LAST:event_windowResizeEvent
    
    public void updateIndividualMenu(JMenuItem selectedMenuItem, int recentElement)
    {
        // Updates a specific menu item
        
        RecentFiles usedFiles = new RecentFiles();
        if ((usedFiles.getRecentFilePath(recentElement)).compareTo("") == 0)
        {
            selectedMenuItem.setVisible(false);
        }
        else
        {
            selectedMenuItem.setVisible(true);
            final String recentFileName = usedFiles.getRecentFileName(recentElement);
            selectedMenuItem.setText(recentFileName);
        }        
    }
    
    public void updateRecentFileList(String newFileName)
    {
    
        // Updates the list of recently used files. If a filename is provided by parameter,
        // the list will include this new file. If not, the list will merely be refreshed
        
        RecentFiles usedFiles = new RecentFiles();
        if (usedFiles.addNewFile(newFileName) == true)
        {
            menuSeparator2.setVisible(true);            
            updateIndividualMenu(lastFileMenuOne,0);
            updateIndividualMenu(lastFileMenuTwo,1);
            updateIndividualMenu(lastFileMenuThree,2);
            updateIndividualMenu(lastFileMenuFour,3);
        }
        else
        {
            if (usedFiles.getNumberFiles() == 0)
            {
                menuSeparator2.setVisible(false);
            }
            else
            {
                menuSeparator2.setVisible(true);
            }
            updateIndividualMenu(lastFileMenuOne,0);
            updateIndividualMenu(lastFileMenuTwo,1);
            updateIndividualMenu(lastFileMenuThree,2);
            updateIndividualMenu(lastFileMenuFour,3);
        }                           
    }       
    
    public void openTrackFile(String fileName)
    {
        
        // Open a track file from a parameter passed filename by using Klaus's track input processing
        
        File trackFile = new File(fileName);
        currentTrack = new Track();
        boolean loadSuccess = currentTrack.load(trackFile);
           
        if (loadSuccess == true)
        {
              
            // Updates the list of recently updated files
                
            updateRecentFileList(fileName);           
                
            // Calculate size of track editing window
                
            int windowX = mainEditorWindow.getWidth();
            int windowY = mainEditorWindow.getHeight();
            TrackWindow newTrackWindow = new TrackWindow(currentTrack, fileName, this);
            newTrackWindow.reshape(0,0,windowX,windowY);
            newTrackWindow.setVisible(true);
                
            // Add track editor window
        
            mainEditorWindow.add(newTrackWindow);
            newTrackWindow.positionWindows();
            newTrackWindow.toFront();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "There was a problem loading the track file specified. \nIt is likely that this is either not a track file, or that the track itself is corrupt.\nPlease try another valid track file", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadTrack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTrack
        // Handles the load track menu item and passes processing onto another method after prompting for a filename
        
        FileDialog fileDialog = new FileDialog(this,true);  
        String fileName = new String();
        boolean cancelCalled = false;
        try
        {
            fileName = fileDialog.showOpenDialog();
        }
        catch (Exception exceptionError)
        {
            cancelCalled = true;
        }
        if (cancelCalled == false)
        {
            openTrackFile(fileName);
        }                
                           
    }//GEN-LAST:event_loadTrack
   
    private void exitProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgram
        // Handles the file menu's exit program function. 
        
        quitChequeredFlag();
        
    }//GEN-LAST:event_exitProgram

    public void quitChequeredFlag()
    {
        // Immediately exits the program after user confirmation
        
        if (closingProgram == false)
        {
            int selectionOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to quit?", "Quit Chequered Flag", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (selectionOption == JOptionPane.YES_OPTION)
            {
                closingProgram = true;
                System.exit(0);
            }       
        }        
    }
    
    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new MainGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem lastFileMenuFour;
    private javax.swing.JMenuItem lastFileMenuOne;
    private javax.swing.JMenuItem lastFileMenuThree;
    private javax.swing.JMenuItem lastFileMenuTwo;
    private javax.swing.JDesktopPane mainEditorWindow;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JSeparator menuSeparator1;
    private javax.swing.JSeparator menuSeparator2;
    private javax.swing.JSeparator menuSeparator3;
    private javax.swing.JMenu openMenu;
    private javax.swing.JMenuItem openTrack;
    private javax.swing.JMenuItem optionsMenu;
    // End of variables declaration//GEN-END:variables
    
}
