/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2006  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * OptionsWindow.java
 *
 * Created on 10 December 2006, 21:30
 */

package chequeredflag.gui;

import java.util.prefs.Preferences;

/**
 *
 * @author  barrie
 */
public class OptionsWindow extends javax.swing.JInternalFrame 
{
    
    private MainGUI mainWindow;
    
    /** Creates new form OptionsWindow */
    public OptionsWindow(MainGUI passedMainWindow) 
    {
        initComponents();
        mainWindow = passedMainWindow;
        interfaceModeSelector.addItem("System Default");
        interfaceModeSelector.addItem("Metal");
        if (System.getProperty("os.name").toUpperCase().indexOf("WINDOWS") != -1)
        {
            interfaceModeSelector.addItem("Windows");            
        }
        if (System.getProperty("os.name").toUpperCase().indexOf("LINUX") != -1)
        {
            interfaceModeSelector.addItem("GTK");
        }
        interfaceModeSelector.addItem("Motif");
        Preferences userData = Preferences.userRoot();
        Preferences cheqFlagData = userData.node("chequeredflag");
        String interfaceSetting = cheqFlagData.get("CFUIMode", "");
        if (interfaceSetting.compareTo("") != 0)
        {
            interfaceModeSelector.setSelectedItem(interfaceSetting);
        }
        System.out.println("Operating System Detected: " + System.getProperty("os.name"));                    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainPanel = new javax.swing.JPanel();
        optionsPanel = new javax.swing.JPanel();
        interfaceModeLabel = new javax.swing.JLabel();
        interfaceModeSelector = new javax.swing.JComboBox();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        mainPanel.setLayout(new java.awt.BorderLayout());

        optionsPanel.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        interfaceModeLabel.setText("Look and Feel Mode");
        optionsPanel.add(interfaceModeLabel);

        optionsPanel.add(interfaceModeSelector);

        mainPanel.add(optionsPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        mainPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel);

        pack();
    }//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Saves all changes and applies chosen settings to the editor
        
        Preferences userData = Preferences.userRoot();
        Preferences cheqFlagData = userData.node("chequeredflag");
        String selectedMode = (String)interfaceModeSelector.getSelectedItem();
        cheqFlagData.put("CFUIMode", selectedMode);
        ThemeManager userInterfaceTheme = new ThemeManager();
        userInterfaceTheme.setUserInterfaceType(selectedMode, mainWindow);
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
           
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Cancels any changes made and closes the form
        
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel interfaceModeLabel;
    private javax.swing.JComboBox interfaceModeSelector;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel optionsPanel;
    // End of variables declaration//GEN-END:variables
    
}
