/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * OptionsWindow.java
 *
 * Created on 10 December 2006, 21:30
 */

package chequeredflag.gui;

import java.util.prefs.Preferences;
import chequeredflag.data.executable.Executable;
import java.io.*;
import javax.swing.*;
import chequeredflag.data.gui.RecentFiles;

/**
 *
 * @author  barrie
 */
public class OptionsWindow extends javax.swing.JInternalFrame 
{
    
    private MainGUI mainWindow;
    
    /** Creates new form OptionsWindow */
    public OptionsWindow(MainGUI passedMainWindow) 
    {
        initComponents();
        mainWindow = passedMainWindow;
        setSize(500,200);
        interfaceModeSelector.addItem("System Default");
        interfaceModeSelector.addItem("Metal");
        if (System.getProperty("os.name").toUpperCase().indexOf("WINDOWS") != -1)
        {
            interfaceModeSelector.addItem("Windows");            
        }
        if (System.getProperty("os.name").toUpperCase().indexOf("LINUX") != -1)
        {
            interfaceModeSelector.addItem("GTK");
        }
        interfaceModeSelector.addItem("Motif");
        Preferences userData = Preferences.userRoot();
        Preferences cheqFlagData = userData.node("chequeredflag");
        String interfaceSetting = cheqFlagData.get("CFUIMode", "");
        if (interfaceSetting.compareTo("") != 0)
        {
            interfaceModeSelector.setSelectedItem(interfaceSetting);
        }
        executableLocation.setText(cheqFlagData.get("EXELocation", ""));
        System.out.println("Operating System Detected: " + System.getProperty("os.name"));                    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lookFeelPanel = new javax.swing.JPanel();
        interfaceModeLabel = new javax.swing.JLabel();
        interfaceModeSelector = new javax.swing.JComboBox();
        executablePanel = new javax.swing.JPanel();
        executableLabelPanel = new javax.swing.JPanel();
        executableLabel = new javax.swing.JLabel();
        executableLocationPanel = new javax.swing.JPanel();
        executableLocation = new javax.swing.JTextField();
        executableSelector = new javax.swing.JButton();
        clearRecent = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        lookFeelPanel.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        interfaceModeLabel.setText("Look and Feel Mode");
        lookFeelPanel.add(interfaceModeLabel);

        lookFeelPanel.add(interfaceModeSelector);

        getContentPane().add(lookFeelPanel);

        executablePanel.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        executableLabelPanel.setLayout(new java.awt.GridLayout(1, 1));

        executableLabel.setText("Location of F1GP/WC Executable");
        executableLabelPanel.add(executableLabel);

        executablePanel.add(executableLabelPanel);

        executableLocationPanel.setLayout(new java.awt.BorderLayout(5, 0));

        executableLocationPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        executableLocation.setColumns(20);
        executableLocationPanel.add(executableLocation, java.awt.BorderLayout.CENTER);

        executableSelector.setText("...");
        executableSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executableSelectorActionPerformed(evt);
            }
        });

        executableLocationPanel.add(executableSelector, java.awt.BorderLayout.EAST);

        executablePanel.add(executableLocationPanel);

        getContentPane().add(executablePanel);

        clearRecent.setText("Clear Recent File List");
        clearRecent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRecentActionPerformed(evt);
            }
        });

        getContentPane().add(clearRecent);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearRecentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRecentActionPerformed
        // Clears the recent file list
        
        int optionSelected = JOptionPane.showConfirmDialog(this, "Are you sure you want to immediately clear the recent file list?", "Clear Recent File List", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (optionSelected == JOptionPane.YES_OPTION)
        {
            RecentFiles usedFiles = new RecentFiles();
            usedFiles.clearRecentFiles();
            mainWindow.updateRecentFileList(""); // Passing empty new file which is flagged up as invalid in this method
        }
        
    }//GEN-LAST:event_clearRecentActionPerformed

    private void executableSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executableSelectorActionPerformed
        // Selects a executable filename
        
        FileDialog fileDialog = new FileDialog(mainWindow,true);  
        fileDialog.setFilterType(2);
        String fileName = new String();
        boolean cancelCalled = false;
        try
        {
            fileName = fileDialog.showOpenDialog();
        }
        catch (Exception exceptionError)
        {
            cancelCalled = true;
        }
        if (cancelCalled == false)
        {
            Executable gameExecutable = new Executable(new File(fileName));
            int exitCode = gameExecutable.loadData();
            switch(exitCode)
            {
                case 0: executableLocation.setText(fileName); break;
                case 1: JOptionPane.showMessageDialog(this, "The file specified is not a known F1GP/WC executable file. This may be because you have \nselected the wrong file, or because this executable has not been updated to version 1.05. \nIn the latter case, upgrading your copy of F1GP/WC to 1.05 will resolve the problem.", "Incompatible Executable Detected", JOptionPane.ERROR_MESSAGE); break;
                case 2: JOptionPane.showMessageDialog(this, "An unknown error has occurred during the loading of this executable file. \nIt is likely that this is either not a F1GP/WC executable file, or that the executable itself is corrupt.\nPlease try a valid executable file", "Unknown Error", JOptionPane.ERROR_MESSAGE); break;
            }
        }        
    }//GEN-LAST:event_executableSelectorActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Saves all changes and applies chosen settings to the editor
        
        Preferences userData = Preferences.userRoot();
        Preferences cheqFlagData = userData.node("chequeredflag");
        String selectedMode = (String)interfaceModeSelector.getSelectedItem();
        cheqFlagData.put("CFUIMode", selectedMode);
        ThemeManager userInterfaceTheme = new ThemeManager();
        userInterfaceTheme.setUserInterfaceType(selectedMode, mainWindow);
        cheqFlagData.put("EXELocation", executableLocation.getText());
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
           
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Cancels any changes made and closes the form
        
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearRecent;
    private javax.swing.JLabel executableLabel;
    private javax.swing.JPanel executableLabelPanel;
    private javax.swing.JTextField executableLocation;
    private javax.swing.JPanel executableLocationPanel;
    private javax.swing.JPanel executablePanel;
    private javax.swing.JButton executableSelector;
    private javax.swing.JLabel interfaceModeLabel;
    private javax.swing.JComboBox interfaceModeSelector;
    private javax.swing.JPanel lookFeelPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    
}
