/*
 * TrackSegmentEditGUI.java
 *
 * Created on 22 May 2005, 22:40
 */

package chequeredflag.gui;

import chequeredflag.data.track.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author  barrie
 */
public class SegmentEditGUI extends javax.swing.JInternalFrame 
{
    
    private TrackWindow parentTrackWindow;
    private TreeEditorWindow parentObjectWindow;
    
    /** Creates new form TrackSegmentEditGUI */
    public SegmentEditGUI(TrackWindow currentTrackWindow, TreeEditorWindow currentObjectWindow) 
    {
        initComponents();
        parentTrackWindow = currentTrackWindow;
        parentObjectWindow = currentObjectWindow;
    }
    
    public void editTrackSegment(TrackSegment trackSegment)
    {
        SegmentTableModel trackData = new SegmentTableModel(trackSegment);
        segmentTable.setRowHeight(20);
        segmentTable.setDefaultRenderer(String.class, new TextTableCellRenderer());
        segmentTable.setDefaultEditor(String.class, new TextTableCellEditor());
        segmentTable.setModel(trackData);
    }
    
    public void editDataHeaders(TrackDataHeader trackHeaders)
    {
        HeaderTableModel headerData = new HeaderTableModel(trackHeaders);
        segmentTable.setRowHeight(20);
        segmentTable.setDefaultRenderer(String.class, new TextTableCellRenderer());
        segmentTable.setDefaultRenderer(JComboBox.class, new SelectionTableCellRenderer());
        segmentTable.setDefaultEditor(String.class, new TextTableCellEditor());
        segmentTable.setDefaultEditor(JComboBox.class, new SelectionTableCellEditor());
        segmentTable.setModel(headerData);
    }
    
    public void editBestLineSegment(CCLineSegment lineSegment)
    {
        BestLineTableModel lineData = new BestLineTableModel(lineSegment);
        segmentTable.setRowHeight(20);
        segmentTable.setDefaultRenderer(String.class, new TextTableCellRenderer());
        segmentTable.setDefaultRenderer(JComboBox.class, new SelectionTableCellRenderer());
        segmentTable.setDefaultEditor(String.class, new TextTableCellEditor());
        segmentTable.setDefaultEditor(JComboBox.class, new SelectionTableCellEditor());
        segmentTable.setModel(lineData);
    }
    
    public void editCmdParams(Command currentCommand, String[] paramText)
    {
        CmdParamTableModel commandData = new CmdParamTableModel(currentCommand, paramText);
        segmentTable.setRowHeight(20);
        segmentTable.setDefaultRenderer(String.class, new TextTableCellRenderer());
        //segmentTable.setDefaultRenderer(JComboBox.class, new SelectionTableCellRenderer());
        segmentTable.setDefaultEditor(String.class, new TextTableCellEditor());
        //segmentTable.setDefaultEditor(JComboBox.class, new SelectionTableCellEditor());
        segmentTable.setModel(commandData);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tableScroll = new javax.swing.JScrollPane();
        segmentTable = new chequeredflag.gui.beans.JExtendedTable();
        buttonPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(463, 350));
        segmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScroll.setViewportView(segmentTable);

        getContentPane().add(tableScroll, java.awt.BorderLayout.CENTER);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 2));

        updateButton.setText("Update Segment");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(updateButton);

        cancelButton.setText("Cancel Changes");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAction(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    public void closeEditorWindow()
    {
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
    }
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Updates the track data with all changes that have been made
        
        if (segmentTable.getModel() instanceof HeaderTableModel)
        {
            HeaderTableModel currentTable = (HeaderTableModel)segmentTable.getModel();
            currentTable.updateTrackData();
            parentTrackWindow.updateTrackMap();
            closeEditorWindow();
            /*try
            {
                this.setClosed(true);
            }
            catch (Exception errorReport)
            {
                // This is a normal result of the closing of an internal window. Nothing should be done.
            }*/
        }        
        else
        {
            if (segmentTable.getModel() instanceof SegmentTableModel)
            {
                SegmentTableModel currentTable = (SegmentTableModel)segmentTable.getModel();
                currentTable.updateTrackData();
                parentTrackWindow.updateTrackMap();
                parentObjectWindow.updateCurrentNode();
                closeEditorWindow();
            }
            else
            {
                if (segmentTable.getModel() instanceof BestLineTableModel)
                {
                    BestLineTableModel currentTable = (BestLineTableModel)segmentTable.getModel();
                    currentTable.updateTrackData();
                    parentTrackWindow.updateTrackMap();
                    parentObjectWindow.updateCurrentNode();
                    closeEditorWindow();
                }
                else
                {
                    if (segmentTable.getModel() instanceof CmdParamTableModel)
                    {
                        CmdParamTableModel currentTable = (CmdParamTableModel)segmentTable.getModel();
                        currentTable.updateTrackData();
                        parentTrackWindow.updateTrackMap();
                        closeEditorWindow();
                    }
                }
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAction
        // Cancels all changes that have been made and closes the window
        
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
        
    }//GEN-LAST:event_cancelAction
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private chequeredflag.gui.beans.JExtendedTable segmentTable;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    
}
