/*
 * TrackPanel.java
 *
 * Created on 30. März 2005, 23:13
 */

package chequeredflag.gui;

import java.awt.*;
import java.awt.geom.*;
import chequeredflag.data.track.*;

/**
 *
 * @author  Klaus
 */
public class TrackPanel extends javax.swing.JPanel {

    static double ANGLE_SCALE_DEG = 360.0 / 65536;
    static double ANGLE_SCALE_RAD = 2 * Math.PI / 65536;

    /** Creates new form TrackPanel */
    public TrackPanel() {
        initComponents();
        standardTrans = new AffineTransform();
        standardTrans.setToIdentity();
        standardTrans.translate(100, 400);
        // Negative Y scale effectively changes Y direction (ascending
        // values from botton to top)
        standardTrans.scale( 1.0, -1.0 );
        // Scaling factor
        m_scale = 1.5;
        // First time drawing flag
        m_fFirstTime = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    public void paintComponent( Graphics g )
    {
        Graphics2D g2d = (Graphics2D) g;
        Dimension d = getSize();

        // fill background
        Color oldColor = g2d.getColor();
        g2d.setColor(getBackground());
        g2d.fillRect(0, 0, d.width, d.height );
        g2d.setColor(oldColor);

        // On first drawing, adjust zooming and panning
        if ( m_fFirstTime )
        {
            m_fFirstTime = false;

            // set zooming and panning values so that track
            // appears in the middle of the window.
            Rectangle r = m_track.getBoundingRectangle();

            // Choose zoom factor so that a border of at least 10 percent
            // remains on each side of the track.
            double dScaleX = d.getWidth() / (r.getWidth() * 1.2);
            double dScaleY = d.getHeight() / (r.getHeight() * 1.2);
            if ( dScaleX > dScaleY )
                m_scale = dScaleY;
            else
                m_scale = dScaleX;

            // Center track in window
            standardTrans.setToIdentity();
            // Negative Y scale effectively changes Y direction (ascending
            // values from botton to top)
            standardTrans.scale( 1.0, -1.0 );
            standardTrans.translate( (d.getWidth() / 2.0) - m_scale * r.getCenterX(),
                                     -(d.getHeight() / 2.0) - m_scale * r.getCenterY() );
        }

        // change drawing direction to have positive y values going up.
        // Also panning could be done by the transformation, but not zooming
        // because automatic zoom looks bad.
        AffineTransform oldTrans = g2d.getTransform();
        g2d.transform( standardTrans );

        // draw all track segments
        TrackSegments trackSegments = m_track.getTrackSegments();
        TrackSegment trackSegment;
        for ( int i = 1; i <= trackSegments.size(); i++ )
        {
            trackSegment = trackSegments.getAt( i );
            if ( trackSegment.getCurvature() == 0 )
            {
                // Straight
/*
                g2d.drawLine( new Double(trackSegment.getPosXStart()).intValue(),
                              new Double(trackSegment.getPosYStart()).intValue(),
                              new Double(trackSegment.getPosXEnd()).intValue(),
                              new Double(trackSegment.getPosYEnd()).intValue() );
*/
                int aXPoints[] = new int[ 4 ];
                int aYPoints[] = new int[ 4 ];
                // Width unit is 1/1024 of TLU.
                double dXDiff = Math.cos( trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
                double dYDiff = Math.sin( trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthStart() / 1024.0;
                aXPoints[ 0 ] = new Double((trackSegment.getPosXStart() - dXDiff) * m_scale).intValue();
                aYPoints[ 0 ] = new Double((trackSegment.getPosYStart() + dYDiff) * m_scale).intValue();
                aXPoints[ 1 ] = new Double((trackSegment.getPosXStart() + dXDiff) * m_scale).intValue();
                aYPoints[ 1 ] = new Double((trackSegment.getPosYStart() - dYDiff) * m_scale).intValue();

                dXDiff = Math.cos( trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
                dYDiff = Math.sin( trackSegment.getAngleStart() * ANGLE_SCALE_RAD ) * trackSegment.getWidthEnd() / 1024.0;
                aXPoints[ 2 ] = new Double((trackSegment.getPosXEnd() + dXDiff) * m_scale).intValue();
                aYPoints[ 2 ] = new Double((trackSegment.getPosYEnd() - dYDiff) * m_scale).intValue();
                aXPoints[ 3 ] = new Double((trackSegment.getPosXEnd() - dXDiff) * m_scale).intValue();
                aYPoints[ 3 ] = new Double((trackSegment.getPosYEnd() + dYDiff) * m_scale).intValue();
                g2d.drawPolygon( aXPoints, aYPoints, 4 );
            }
            else
            {
                // Curve
                if ( trackSegment.getCurvature() > 0 )
                {
                    // right turn
                    g2d.drawArc( new Double((trackSegment.getPosXCenter() - trackSegment.getRadius()) * m_scale).intValue(),
                                 new Double((trackSegment.getPosYCenter() - trackSegment.getRadius()) * m_scale).intValue(),
                                 new Double((trackSegment.getRadius() * 2) * m_scale).intValue(),
                                 new Double((trackSegment.getRadius() * 2) * m_scale).intValue(),
                                 new Double(180.0 + trackSegment.getAngleStart() * ANGLE_SCALE_DEG).intValue(),
                                 new Double((trackSegment.getAngleEnd() - trackSegment.getAngleStart()) * ANGLE_SCALE_DEG).intValue() );
                }
                else
                {
                    // left turn means negative radius!
                    g2d.drawArc( new Double((trackSegment.getPosXCenter() + trackSegment.getRadius()) * m_scale).intValue(),
                                 new Double((trackSegment.getPosYCenter() + trackSegment.getRadius()) * m_scale).intValue(),
                                 new Double((trackSegment.getRadius() * -2) * m_scale).intValue(),
                                 new Double((trackSegment.getRadius() * -2) * m_scale).intValue(),
                                 new Double(trackSegment.getAngleStart() * ANGLE_SCALE_DEG).intValue(),
                                 new Double((trackSegment.getAngleEnd() - trackSegment.getAngleStart()) * ANGLE_SCALE_DEG).intValue() );
                }
            }
        }

        // reset transformations
        g2d.setTransform( oldTrans );
    }

    private Track m_track;
    private AffineTransform standardTrans;
    private double m_scale;
    private boolean m_fFirstTime;

    public void setTrack(Track track) {
        m_track = track;
        m_fFirstTime = true; // trigger calculations on first drawing
    }

    public void zoomIn() {
        m_scale = m_scale * 1.5;
        Dimension d = getSize();
        repaint(0, 0, 0, d.width, d.height );
    }

    public void zoomOut() {
        m_scale = m_scale / 1.5;
        Dimension d = getSize();
        repaint(0, 0, 0, d.width, d.height );
    }

    public void panX( int nXPan ) {
        standardTrans.translate( nXPan, 0 );
        Dimension d = getSize();
        repaint(0, 0, 0, d.width, d.height );
    }

    public void panY( int nYPan ) {
        standardTrans.translate( 0, nYPan );
        Dimension d = getSize();
        repaint(0, 0, 0, d.width, d.height );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
