/*
 * TrackSegmentEditGUI.java
 *
 * Created on 13 May 2005, 18:46
 */

package chequeredflag.gui;

import chequeredflag.data.track.*;
import javax.swing.table.*;
import chequeredflag.gui.beans.JExtendedTable;

/**
 *
 * @author  barrie
 */
public class TrackSegmentEditGUI extends javax.swing.JDialog {
    
    /** Creates new form TrackSegmentEditGUI */
    public TrackSegmentEditGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(300,200);
    }
    
    public void editTrackSegment(TrackSegment trackSegment)
    {
        SegmentTableModel trackData = new SegmentTableModel(trackSegment);
        segmentEdit.setModel(trackData);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        segmentEdit = new chequeredflag.gui.beans.JExtendedTable();
        descriptionText = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        saveChanges = new javax.swing.JButton();
        cancelChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        segmentEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        getContentPane().add(segmentEdit, java.awt.BorderLayout.CENTER);

        descriptionText.setText("Editing Segment...");
        getContentPane().add(descriptionText, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 2));

        saveChanges.setText("Save Changes");
        buttonPanel.add(saveChanges);

        cancelChanges.setText("Cancel Changes");
        buttonPanel.add(cancelChanges);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackSegmentEditGUI(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelChanges;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JButton saveChanges;
    private chequeredflag.gui.beans.JExtendedTable segmentEdit;
    // End of variables declaration//GEN-END:variables
    
}
