/*
 * TrackPanel.java
 *
 * Created on 30. März 2005, 23:13
 */

package chequeredflag.gui;

import java.awt.*;
import java.awt.geom.*;
import chequeredflag.data.track.*;

/**
 *
 * @author  Klaus
 */
public class TrackPanel extends javax.swing.JPanel {

    static double ANGLE_SCALE = 360.0 / 65536;

    /** Creates new form TrackPanel */
    public TrackPanel() {
        initComponents();
        standardTrans = new AffineTransform();
        standardTrans.setToIdentity();
        standardTrans.translate(100, 400);
        // Negative Y scale effectively changes Y direction (ascending
        // values from botton to top)
        standardTrans.scale( 1.5, -1.5 );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents

    public void paintComponent( Graphics g )
    {
        Graphics2D g2d = (Graphics2D) g;
        Dimension d = getSize();

        // fill background
        Color oldColor = g2d.getColor();
        g2d.setColor(getBackground());
        g2d.fillRect(0, 0, d.width, d.height );
        g2d.setColor(oldColor);

        // apply zooming and moving of the track display
        AffineTransform oldTrans = g2d.getTransform();
        g2d.transform( standardTrans );

        // draw all track segments
        TrackSegments trackSegments = m_track.getTrackSegments();
        TrackSegment trackSegment;
        for ( int i = 1; i <= trackSegments.size(); i++ )
        {
            trackSegment = trackSegments.getAt( i );
            if ( trackSegment.getCurvature() == 0 )
            {
                // Straight
                g2d.drawLine( new Double(trackSegment.getPosXStart()).intValue(),
                              new Double(trackSegment.getPosYStart()).intValue(),
                              new Double(trackSegment.getPosXEnd()).intValue(),
                              new Double(trackSegment.getPosYEnd()).intValue() );
            }
            else
            {
                // Curve
                if ( trackSegment.getCurvature() > 0 )
                {
                    // right turn
                    g2d.drawArc( new Double(trackSegment.getPosXCenter() - trackSegment.getRadius()).intValue(),
                                 new Double(trackSegment.getPosYCenter() - trackSegment.getRadius()).intValue(),
                                 new Double(trackSegment.getRadius() * 2).intValue(),
                                 new Double(trackSegment.getRadius() * 2).intValue(),
                                 new Double(180.0 + trackSegment.getAngleStart() * ANGLE_SCALE).intValue(),
                                 new Double((trackSegment.getAngleEnd() - trackSegment.getAngleStart()) * ANGLE_SCALE).intValue() );
                }
                else
                {
                    // left turn means negative radius!
                    g2d.drawArc( new Double(trackSegment.getPosXCenter() + trackSegment.getRadius()).intValue(),
                                 new Double(trackSegment.getPosYCenter() + trackSegment.getRadius()).intValue(),
                                 new Double(trackSegment.getRadius() * -2).intValue(),
                                 new Double(trackSegment.getRadius() * -2).intValue(),
                                 new Double(trackSegment.getAngleStart() * ANGLE_SCALE).intValue(),
                                 new Double((trackSegment.getAngleEnd() - trackSegment.getAngleStart()) * ANGLE_SCALE).intValue() );
                }
            }
        }

        // reset transformations
        g2d.setTransform( oldTrans );
    }

    private Track m_track;
    private AffineTransform standardTrans;

    public void setTrack(Track track) {
        m_track = track;
    }

    public void zoomIn() {
        standardTrans.scale(1.1, 1.1);
        Dimension d = getSize();
        repaint(0, 0, 0, d.width, d.height );
    }

    public void zoomOut() {
        standardTrans.scale(0.9, 0.9);
        Dimension d = getSize();
        repaint(0, 0, 0, d.width, d.height );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
