/*
 * TrackGUI.java
 *
 * Created on 22 February 2005, 22:28
 */

package chequeredflag.gui;

import javax.swing.*;
import java.io.*;
import chequeredflag.data.track.*;

/**
 *
 * @author  barrie
 */
public class TrackGUI extends javax.swing.JFrame 
{
    
    private Track currentTrack;
    private TreeEditorWindow treeWindow;
    private GraphicalEditorWindow mapWindow;
        
    /** Creates new form TrackGUI */
    public TrackGUI() 
    {
        // Setting main frame information
        super("Chequered Flag - An open-source F1GP/WC editor");
        initComponents();
        setSize(576,432);
        setVisible(true);
        treeWindow = new TreeEditorWindow();
        mapWindow = new GraphicalEditorWindow();
        setContentPane(mainEditorWindow);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        mainEditorWindow = new javax.swing.JDesktopPane();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openTrack = new javax.swing.JMenuItem();
        saveTrack = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JSeparator();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResizeEvent(evt);
            }
        });

        getContentPane().add(mainEditorWindow);

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        openTrack.setText("Open F1GP/WC Track");
        openTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTrackFile(evt);
            }
        });

        fileMenu.add(openTrack);

        saveTrack.setText("Save F1GP/WC Track");
        saveTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTrackFile(evt);
            }
        });

        fileMenu.add(saveTrack);

        fileMenu.add(menuSeparator1);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgram(evt);
            }
        });

        fileMenu.add(exitItem);

        mainMenuBar.add(fileMenu);

        helpMenu.setText("Help");
        aboutItem.setText("About");
        aboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAbout(evt);
            }
        });

        helpMenu.add(aboutItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }//GEN-END:initComponents

    private void saveTrackFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTrackFile
        // Saves the current track file in memory by using ksix's track output processing
        
        FileDialog fileDialog = new FileDialog(this,true);
        String fileName = fileDialog.showSaveDialog();
        if (fileName.toLowerCase().endsWith(".dat") == false)
        {
                fileName = fileName + ".DAT";
        }
        File trackFile = new File(fileName);
        currentTrack.save(trackFile);
    }//GEN-LAST:event_saveTrackFile

    private void windowResizeEvent(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResizeEvent
        // Detects any change in the size of the main editor window and adjusts internal frames accordingly
        
        positionWindows();
        
    }//GEN-LAST:event_windowResizeEvent

    private void openTrackFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTrackFile
        // Opens a new track file and reads in data by using ksix's track input processing
        
        FileDialog fileDialog = new FileDialog(this,true);  
        String fileName = fileDialog.showOpenDialog();
        File trackFile = new File(fileName);
        currentTrack = new Track();
        currentTrack.load(trackFile);
        positionWindows();
        mainEditorWindow.add(treeWindow);
        mainEditorWindow.add(mapWindow);
        treeWindow.setVisible(true);
        mapWindow.setVisible(true);
    
    }//GEN-LAST:event_openTrackFile

    private void positionWindows()
    {
        // Re-positions and Re-sizes internal frames by considering the size of the main frame
        
        int windowX = mainEditorWindow.getWidth();
        int windowY = mainEditorWindow.getHeight();
        int treeX = new Double(windowX * 0.4).intValue();
        treeWindow.reshape(0,0,treeX,windowY);
        mapWindow.reshape(treeX+1,0,windowX-(treeX+1), windowY);
    }
        
    private void displayAbout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAbout
        // Displays the About dialog
        
        AboutGUI aboutDialog = new AboutGUI();
                
    }//GEN-LAST:event_displayAbout

    private void exitProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgram
        // Immediately exits the program with no further steps
        
        System.exit(0);
        
    }//GEN-LAST:event_exitProgram

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new TrackGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JDesktopPane mainEditorWindow;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JSeparator menuSeparator1;
    private javax.swing.JMenuItem openTrack;
    private javax.swing.JMenuItem saveTrack;
    // End of variables declaration//GEN-END:variables
    
}
