/*
 * TrackWindow.java
 *
 * Created on 07 April 2005, 03:43
 */

package chequeredflag.gui;

import java.io.*;
import chequeredflag.data.track.*;
import javax.swing.*;
import javax.swing.event.InternalFrameListener;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author  barrie
 */

/* Class designed to manage both the treeview and track map windows */

public class TrackWindow extends javax.swing.JInternalFrame implements InternalFrameListener
{
    
    private Track currentTrack;
    private TreeEditorWindow treeWindow;
    private GraphicalEditorWindow mapWindow;
    private MainGUI appFrame;
    private String fileName;
    private boolean closingWindow;
    
    /** Creates new form TrackWindow */
    /* Receives a selected track as input */
    public TrackWindow(Track selectedTrack, String trackFileName, MainGUI origContainer) 
    {
        super("Track File: " + trackFileName);
        fileName = trackFileName;
        initComponents();
        setContentPane(trackEditorWindow);
        currentTrack = selectedTrack;
        appFrame = origContainer;
        treeWindow = new TreeEditorWindow(trackEditorWindow, this);
        mapWindow = new GraphicalEditorWindow();
        mapWindow.setTrack(currentTrack);
        treeWindow.setTrack(currentTrack);
        treeWindow.populateTree();
        trackEditorPane.setLeftComponent(treeWindow);
        trackEditorPane.setRightComponent(mapWindow);
        treeWindow.setVisible(true);
        mapWindow.setVisible(true);
        addInternalFrameListener(this); // Listener for internal frame closing events
        closingWindow = false; // Boolean value for detecting if closing occurs and then blocks any further events
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); // Handle close operations manually
    }
    
    public void internalFrameClosing(InternalFrameEvent e) 
    {
        // Handle window closing event
        
        closeTrack();
    }
    
    public void closeTrack()
    {
        // Close the open track window after user confirmation
        
        if (closingWindow == false)
        {
            int selectionOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this track?", "Close Track", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (selectionOption == JOptionPane.YES_OPTION)
            {
                try
                {
                    closingWindow = true;
                    this.setClosed(true);
                }
                catch (Exception errorReport)
                {
                    // This is a normal result of the closing of an internal window. Nothing should be done.
                }
            }       
        }
    }

    public void internalFrameClosed(InternalFrameEvent e) 
    {
	//listenedToWindow = null;
    }

    public void internalFrameOpened(InternalFrameEvent e) 
    {
    }

    public void internalFrameIconified(InternalFrameEvent e) 
    {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) 
    {
    }

    public void internalFrameActivated(InternalFrameEvent e) 
    {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) 
    {
    }
    
    public void positionWindows()
    {
        // Re-position and resize internal windows based on size of main track window
        
        int windowX = trackEditorWindow.getWidth();
        int windowY = trackEditorWindow.getHeight();
        trackEditorPane.reshape(0,0,windowX,windowY);
        trackEditorPane.setDividerLocation(0.42);
        trackEditorPane.updateUI();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        trackEditorWindow = new javax.swing.JDesktopPane();
        trackEditorPane = new javax.swing.JSplitPane();
        trackMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveTrackItem = new javax.swing.JMenuItem();
        saveTrackAsItem = new javax.swing.JMenuItem();
        closeTrackItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        removeTrack = new javax.swing.JMenuItem();
        removePit = new javax.swing.JMenuItem();
        removeLine = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResize(evt);
            }
        });

        trackEditorPane.setBounds(0, 0, -1, -1);
        trackEditorWindow.add(trackEditorPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(trackEditorWindow);

        fileMenu.setText("File");
        saveTrackItem.setText("Save Track...");
        saveTrackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTrackItem(evt);
            }
        });

        fileMenu.add(saveTrackItem);

        saveTrackAsItem.setText("Save Track As...");
        saveTrackAsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTrackAs(evt);
            }
        });

        fileMenu.add(saveTrackAsItem);

        closeTrackItem.setText("Close Track");
        closeTrackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTrackItemActionPerformed(evt);
            }
        });

        fileMenu.add(closeTrackItem);

        trackMenuBar.add(fileMenu);

        toolsMenu.setText("Tools");
        removeTrack.setText("Remove All Track Segments");
        removeTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllTrack(evt);
            }
        });

        toolsMenu.add(removeTrack);

        removePit.setText("Remove All Pit Segments");
        removePit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllPit(evt);
            }
        });

        toolsMenu.add(removePit);

        removeLine.setText("Remove All Best Line Segments");
        removeLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllLine(evt);
            }
        });

        toolsMenu.add(removeLine);

        trackMenuBar.add(toolsMenu);

        setJMenuBar(trackMenuBar);

        pack();
    }//GEN-END:initComponents

    private void removeAllLine(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllLine
        // Handles line removal menu event
        
        int selectionOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove all best line segments?", "Clear Best Line", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (selectionOption == JOptionPane.YES_OPTION)
        {
            treeWindow.deleteAllSegments(2);
        }
        
    }//GEN-LAST:event_removeAllLine

    private void removeAllPit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllPit
        // Handles pit removal menu event
        
        int selectionOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove all pit segments?", "Clear Pit Segments", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (selectionOption == JOptionPane.YES_OPTION)
        {
            treeWindow.deleteAllSegments(1);
        }
        
    }//GEN-LAST:event_removeAllPit

    private void removeAllTrack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllTrack
        // Handles track removal menu event
        
        int selectionOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove all track segments?", "Clear Track Segments", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (selectionOption == JOptionPane.YES_OPTION)
        {
            treeWindow.deleteAllSegments(0);
        }
        
    }//GEN-LAST:event_removeAllTrack

    private void closeTrackItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTrackItemActionPerformed
        // Handle close track menu event
        
        closeTrack();      
        
    }//GEN-LAST:event_closeTrackItemActionPerformed

    public void updateTrackMap()
    {
        // Send a command through the object model to update the track map.
        // Should really use interfaces for this, but this involves less thinking for now.
        
        mapWindow.redrawTrackMap();
        
    }
    
    public void highlightSection(int sectionType, int segmentNo)
    {
        // Sends a command through the object model to highlight a section of the track map
        // Should really use interfaces for this, but this involves less thinking for now.
        
        mapWindow.selectedSegment(sectionType, segmentNo);
        
    }
    
    private void saveTrackItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTrackItem
        // Saves the current track file to the same file it was loaded from
        // FUTURE: New track files will have no existing filename and therefore will need to be routed to saveTrackAs
        
        File trackFile = new File(fileName);
        currentTrack.save(trackFile);
        
    }//GEN-LAST:event_saveTrackItem
    
    private void saveTrackAs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTrackAs
        // Prompts for a filename and then saves the current track file in memory to the specified filename
        
        boolean cancelCalled = false;
        String selectedFileName = new String();
        FileDialog fileDialog = new FileDialog(appFrame,true);
        try
        {
            selectedFileName = fileDialog.showSaveDialog();
        }
        catch (Exception exceptionError)
        {
            cancelCalled = true;
        }
        if (cancelCalled == false)
        {
            if (selectedFileName.toLowerCase().endsWith(".dat") == false)
            {
                    selectedFileName = selectedFileName + ".DAT";
            }
            File fileTest = new File(selectedFileName);
            if (fileTest.exists() == true)
            {
                JOptionPane.showMessageDialog(this, "The filename you have provided already exists. Please try again.", "Filename already exists", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File trackFile = new File(selectedFileName);
                currentTrack.save(trackFile);
            }
        }
    }//GEN-LAST:event_saveTrackAs

    private void windowResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResize
        // Calls window location and size re-calculation code when internal frame is resized.
        
        positionWindows();
        
        
    }//GEN-LAST:event_windowResize
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeTrackItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem removeLine;
    private javax.swing.JMenuItem removePit;
    private javax.swing.JMenuItem removeTrack;
    private javax.swing.JMenuItem saveTrackAsItem;
    private javax.swing.JMenuItem saveTrackItem;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JSplitPane trackEditorPane;
    private javax.swing.JDesktopPane trackEditorWindow;
    private javax.swing.JMenuBar trackMenuBar;
    // End of variables declaration//GEN-END:variables
    
}
