/*
 * TrackWindow.java
 *
 * Created on 07 April 2005, 03:43
 */

package chequeredflag.gui;

import java.io.*;
import chequeredflag.data.track.*;

/**
 *
 * @author  barrie
 */

/* Class designed to manage both the treeview and track map windows */

public class TrackWindow extends javax.swing.JInternalFrame {
    
    private Track currentTrack;
    private TreeEditorWindow treeWindow;
    private GraphicalEditorWindow mapWindow;
    private MainGUI mainFrame;
    
    /** Creates new form TrackWindow */
    /* Receives a selected track as input */
    public TrackWindow(Track selectedTrack, String fileName, MainGUI originalFrame) 
    {
        super("Track File: " + fileName);
        initComponents();
        setContentPane(trackEditorWindow);
        currentTrack = selectedTrack;
        mainFrame = originalFrame;
        treeWindow = new TreeEditorWindow(mainFrame);
        mapWindow = new GraphicalEditorWindow();
        mapWindow.setTrack(currentTrack);
        treeWindow.setTrack(currentTrack);
        treeWindow.populateTree();
        trackEditorWindow.add(treeWindow);
        trackEditorWindow.add(mapWindow);
        treeWindow.setVisible(true);
        mapWindow.setVisible(true);
        
    }
    
    private void positionWindows()
    {
        // Re-position and resize internal windows based on size of main track window
        
        int windowX = trackEditorWindow.getWidth();
        int windowY = trackEditorWindow.getHeight();
        int halfX = new Double(windowX/2).intValue();
        treeWindow.reshape(0,0,halfX,windowY);
        mapWindow.reshape(halfX+1,0,windowX-(halfX+1),windowY);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        trackEditorWindow = new javax.swing.JDesktopPane();
        trackMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveTrackItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResize(evt);
            }
        });

        getContentPane().add(trackEditorWindow);

        fileMenu.setText("File");
        saveTrackItem.setText("Save Track...");
        saveTrackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTrack(evt);
            }
        });

        fileMenu.add(saveTrackItem);

        trackMenuBar.add(fileMenu);

        setJMenuBar(trackMenuBar);

        pack();
    }//GEN-END:initComponents

    private void saveTrack(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTrack
        // Saves the current track file in memory by using ksix's track output processing
        
        // Warning: No overwrite checking code in place yet
        
        FileDialog fileDialog = new FileDialog(mainFrame,true);
        String fileName = fileDialog.showSaveDialog();
        if (fileName.toLowerCase().endsWith(".dat") == false)
        {
                fileName = fileName + ".DAT";
        }
        File trackFile = new File(fileName);
        currentTrack.save(trackFile);
    }//GEN-LAST:event_saveTrack

    private void windowResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResize
        // Calls window location and size re-calculation code when internal frame is resized.
        
        positionWindows();
        
        
    }//GEN-LAST:event_windowResize
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem saveTrackItem;
    private javax.swing.JDesktopPane trackEditorWindow;
    private javax.swing.JMenuBar trackMenuBar;
    // End of variables declaration//GEN-END:variables
    
}
