/*
 * TrackWindow.java
 *
 * Created on 07 April 2005, 03:43
 */

package chequeredflag.gui;

import java.io.*;
import chequeredflag.data.track.*;
import javax.swing.*;

/**
 *
 * @author  barrie
 */

/* Class designed to manage both the treeview and track map windows */

public class TrackWindow extends javax.swing.JInternalFrame {
    
    private Track currentTrack;
    private TreeEditorWindow treeWindow;
    private GraphicalEditorWindow mapWindow;
    private MainGUI appFrame;
    private String fileName;
    
    /** Creates new form TrackWindow */
    /* Receives a selected track as input */
    public TrackWindow(Track selectedTrack, String trackFileName, MainGUI origContainer) 
    {
        super("Track File: " + trackFileName);
        fileName = trackFileName;
        initComponents();
        setContentPane(trackEditorWindow);
        currentTrack = selectedTrack;
        appFrame = origContainer;
        treeWindow = new TreeEditorWindow(trackEditorWindow, this);
        mapWindow = new GraphicalEditorWindow();
        mapWindow.setTrack(currentTrack);
        treeWindow.setTrack(currentTrack);
        treeWindow.populateTree();
        trackEditorWindow.add(treeWindow);
        trackEditorWindow.add(mapWindow);
        treeWindow.setVisible(true);
        mapWindow.setVisible(true);
        
    }
    
    private void positionWindows()
    {
        // Re-position and resize internal windows based on size of main track window
        
        int windowX = trackEditorWindow.getWidth();
        int windowY = trackEditorWindow.getHeight();
        int halfX = new Double(windowX/2).intValue();
        treeWindow.reshape(0,0,halfX,windowY);
        mapWindow.reshape(halfX+1,0,windowX-(halfX+1),windowY);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        trackEditorWindow = new javax.swing.JDesktopPane();
        trackMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveTrackItem = new javax.swing.JMenuItem();
        saveTrackAsItem = new javax.swing.JMenuItem();
        closeTrackItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResize(evt);
            }
        });

        getContentPane().add(trackEditorWindow);

        fileMenu.setText("File");
        saveTrackItem.setText("Save Track...");
        saveTrackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTrackItem(evt);
            }
        });

        fileMenu.add(saveTrackItem);

        saveTrackAsItem.setText("Save Track As...");
        saveTrackAsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTrackAs(evt);
            }
        });

        fileMenu.add(saveTrackAsItem);

        closeTrackItem.setText("Close Track");
        closeTrackItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeTrackItemActionPerformed(evt);
            }
        });

        fileMenu.add(closeTrackItem);

        trackMenuBar.add(fileMenu);

        setJMenuBar(trackMenuBar);

        pack();
    }//GEN-END:initComponents

    private void closeTrackItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeTrackItemActionPerformed
        // Close the track file
        
        try
        {
            this.setClosed(true);
        }
        catch (Exception errorReport)
        {
            // This is a normal result of the closing of an internal window. Nothing should be done.
        }
    }//GEN-LAST:event_closeTrackItemActionPerformed

    public void updateTrackMap()
    {
        // Send a command through the object model to update the track map.
        // Should really use interfaces for this, but this involves less thinking for now.
        
        mapWindow.redrawTrackMap();
        
    }
    
    private void saveTrackItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTrackItem
        // Saves the current track file to the same file it was loaded from
        // FUTURE: New track files will have no existing filename and therefore will need to be routed to saveTrackAs
        
        File trackFile = new File(fileName);
        currentTrack.save(trackFile);
        
    }//GEN-LAST:event_saveTrackItem
    
    private void saveTrackAs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTrackAs
        // Prompts for a filename and then saves the current track file in memory to the specified filename
        
        boolean cancelCalled = false;
        String selectedFileName = new String();
        FileDialog fileDialog = new FileDialog(appFrame,true);
        try
        {
            selectedFileName = fileDialog.showSaveDialog();
        }
        catch (Exception exceptionError)
        {
            cancelCalled = true;
        }
        if (cancelCalled == false)
        {
            if (selectedFileName.toLowerCase().endsWith(".dat") == false)
            {
                    selectedFileName = selectedFileName + ".DAT";
            }
            File fileTest = new File(selectedFileName);
            if (fileTest.exists() == true)
            {
                JOptionPane.showMessageDialog(this, "The filename you have provided already exists. Please try again.", "Filename already exists", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                File trackFile = new File(selectedFileName);
                currentTrack.save(trackFile);
            }
        }
    }//GEN-LAST:event_saveTrackAs

    private void windowResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResize
        // Calls window location and size re-calculation code when internal frame is resized.
        
        positionWindows();
        
        
    }//GEN-LAST:event_windowResize
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeTrackItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem saveTrackAsItem;
    private javax.swing.JMenuItem saveTrackItem;
    private javax.swing.JDesktopPane trackEditorWindow;
    private javax.swing.JMenuBar trackMenuBar;
    // End of variables declaration//GEN-END:variables
    
}
