/*
 * TreeEditorWindow.java
 *
 * Created on 24 March 2005, 01:26
 */

package chequeredflag.gui;

import javax.swing.tree.*;

/**
 *
 * @author  barrie
 */
public class TreeEditorWindow extends javax.swing.JInternalFrame {
    
    private DefaultMutableTreeNode rootNode;
    
    /** Creates new form TreeEditorWindow */
    public TreeEditorWindow() {
        initComponents();
        setDefaultElement();    
        createTree();
    }
    
    private void setDefaultElement()
    {
        // Adds a single root node to the tree as part of initial configuration.
        rootNode = new DefaultMutableTreeNode("Track Data");        
    }
    
    private void createTree()
    {
        // Writes all current tree nodes to the tree interface
        
        trackDetails.setModel(new DefaultTreeModel(rootNode));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        trackDetails = new javax.swing.JTree();

        getContentPane().add(trackDetails, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree trackDetails;
    // End of variables declaration//GEN-END:variables
    
}
