/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * JExtendedTable.java
 *
 * Created on 14 May 2005, 02:53
 */

package chequeredflag.gui.table;

import javax.swing.table.*;
import java.io.*;

/**
 *
 * @author  barrie
 */

// Extension of JTable created to allow the use of multiple data representations in a single column. 

public class JExtendedTable extends javax.swing.JTable implements Serializable
{ // Serializable had to be manually added and is a requirement for making use of beans.
    
    // To be an official bean, all variables must be supplied with getXXX and setXXX methods. 
    
    // Added to Netbeans by use of "Add to Palette..." option in the Tools menu. Selected class is then added by default.
    
    /** Creates new form BeanForm */
    public JExtendedTable() 
    {
        super(); // Possibly required for bean operation
        initComponents();
    }
    
    public TableCellRenderer getCellRenderer(int row, int column) 
    {
        Object dataValue = getValueAt(row,column);
        if (dataValue != null)
        {
            return getDefaultRenderer(dataValue.getClass());
        }
        return super.getCellRenderer(row,column);
    }
    
    public TableCellEditor getCellEditor(int row, int column)
    {
        Object dataValue = getValueAt(row,column);
        if (dataValue != null)
        {
            return getDefaultEditor(dataValue.getClass());
        }
        return super.getCellEditor(row,column);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
