/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * ExecutableTreeSelector.java
 *
 * Created on 31 December 2006, 20:03
 */

package chequeredflag.gui.executable;

import chequeredflag.data.track.*;
import javax.swing.*;
import chequeredflag.data.executable.*;
import javax.swing.tree.*;

/**
 *
 * @author  barrie
 */
public class ExecutableTreeSelector extends javax.swing.JInternalFrame 
{
    
    private JDesktopPane parentFrame;
    private ExecutableWindow parentExecutableWindow;
    private DefaultMutableTreeNode rootNode;
    private Executable currentExecutable;
    
    /** Creates new form ExecutableTreeSelector */
    public ExecutableTreeSelector(JDesktopPane containerFrame, ExecutableWindow currentExecutableWindow) 
    {
        initComponents();
        setDefaultElements();
        createTree();
        parentFrame = containerFrame;
        parentExecutableWindow = currentExecutableWindow;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        treeViewScroll = new javax.swing.JScrollPane();
        executableSelector = new javax.swing.JTree();

        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        executableSelector.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                setSelectedNode(evt);
            }
        });

        treeViewScroll.setViewportView(executableSelector);

        getContentPane().add(treeViewScroll);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setSelectedNode(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_setSelectedNode

        // Handles the event when a tree note is selected
        
        TreePath fullPath = executableSelector.getSelectionPath();
        try 
        {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode)fullPath.getLastPathComponent();
            if (selectedNode.toString() == "Game Options")
            {
                parentExecutableWindow.changePage(3);
            }
            else
            {
                if (selectedNode.toString() == "Game Settings")
                {
                    parentExecutableWindow.changePage(2);
                }
                else
                {
                    if (selectedNode.toString() == "Executable Data")
                    {
                        parentExecutableWindow.changePage(1);
                    }
                    else
                    {
                        if (selectedNode.toString() == "Points")
                        {
                            parentExecutableWindow.changePage(4);
                        }
                        else
                        {
                            if (selectedNode.toString() == "Drivers")
                            {
                                parentExecutableWindow.changePage(5);
                            }
                        }
                    }
                }
            }
        }
        catch (Exception exceptionError)
        {
            // No tree item selected, so exception thrown
        }    
    }//GEN-LAST:event_setSelectedNode
    
    private void setDefaultElements()
    {
        // Creates the default tree as part of initial configuration.
        rootNode = new DefaultMutableTreeNode("Executable Data");
        DefaultMutableTreeNode gamePoints = new DefaultMutableTreeNode("Points");
        rootNode.add(gamePoints);
        DefaultMutableTreeNode gameSettings = new DefaultMutableTreeNode("Game Settings");
        rootNode.add(gameSettings);
        DefaultMutableTreeNode gameOptions = new DefaultMutableTreeNode("Game Options");
        rootNode.add(gameOptions);
        DefaultMutableTreeNode gameDrivers = new DefaultMutableTreeNode("Drivers");
        rootNode.add(gameDrivers);
    }
    
    private void createTree()
    {
        // Writes all current tree nodes to the tree interface
        
        executableSelector.setModel(new DefaultTreeModel(rootNode));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree executableSelector;
    private javax.swing.JScrollPane treeViewScroll;
    // End of variables declaration//GEN-END:variables
    
}
