/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * ExecutableWindow.java
 *
 * Created on 31 December 2006, 04:21
 */

package chequeredflag.gui.executable;

import chequeredflag.gui.*;
import chequeredflag.gui.executable.panels.*;
import javax.swing.event.InternalFrameListener;
import javax.swing.event.InternalFrameEvent;
import javax.swing.*;
import java.awt.*;
import chequeredflag.data.executable.*;

/**
 *
 * @author  barrie
 */
public class ExecutableWindow extends javax.swing.JInternalFrame implements InternalFrameListener
{
    
    private boolean closingWindow;
    private MainGUI appFrame;
    private String fileName;
    private Executable currentExecutable;
    private ExecutableTreeSelector executableSelector;
    private JPanel multiPageContainer;
    private GameOptionsPanel gameOptions;
    private GameSettingsPanel gameSettings;
    private GamePointsPanel gamePoints;
    private GameDriversPanel gameDrivers;
    private CardLayout cardLayout;
    
    /** Creates new form ExecutableWindow */
    public ExecutableWindow(Executable selectedExecutable, String executableFileName, MainGUI origContainer) 
    {
        super("Executable File: " + executableFileName);
        fileName = executableFileName;
        initComponents();
        setContentPane(executableEditorWindow);
        currentExecutable = selectedExecutable;
        appFrame = origContainer;
        executableSelector = new ExecutableTreeSelector(executableEditorWindow, this);
        cardLayout = new CardLayout();
        multiPageContainer = new JPanel();
        multiPageContainer.setLayout(cardLayout);
        executableEditorPane.setLeftComponent(executableSelector);
        executableEditorPane.setRightComponent(multiPageContainer);
        gameOptions = new GameOptionsPanel(currentExecutable.getGameOptions());
        gameSettings = new GameSettingsPanel(currentExecutable.getGameSettings());
        gamePoints = new GamePointsPanel(currentExecutable.getGamePoints(), currentExecutable.returnGameVersionID()); 
        gameDrivers = new GameDriversPanel(currentExecutable.getGameDrivers());
        ExecutableInfoPanel executableInfo = new ExecutableInfoPanel(currentExecutable.returnGameVersionString());
        multiPageContainer.add("Executable Info", executableInfo);
        multiPageContainer.add("Game Settings", gameSettings);
        multiPageContainer.add("Game Options", gameOptions);
        multiPageContainer.add("Points", gamePoints);
        multiPageContainer.add("Drivers", gameDrivers);
        ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Executable Info");
        executableSelector.setVisible(true);
        multiPageContainer.setVisible(true);
        addInternalFrameListener(this); // Listener for internal frame closing events
        closingWindow = false; // Boolean value for detecting if closing occurs and then blocks any further events
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); // Handle close operations manually        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        executableEditorWindow = new javax.swing.JDesktopPane();
        executableEditorPane = new javax.swing.JSplitPane();
        executableMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveExecutableItem = new javax.swing.JMenuItem();
        closeExecutableItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(600, 400));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                windowResize(evt);
            }
        });

        executableEditorPane.setBounds(0, 0, -1, -1);
        executableEditorWindow.add(executableEditorPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(executableEditorWindow);

        fileMenu.setText("File");
        saveExecutableItem.setText("Save Executable...");
        saveExecutableItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveExecutableItemActionPerformed(evt);
            }
        });

        fileMenu.add(saveExecutableItem);

        closeExecutableItem.setText("Close Executable");
        closeExecutableItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeExecutableItemActionPerformed(evt);
            }
        });

        fileMenu.add(closeExecutableItem);

        executableMenuBar.add(fileMenu);

        setJMenuBar(executableMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_windowResize

        // Calls window location and size re-calculation code when internal frame is resized.
        
        positionWindows();
        
    }//GEN-LAST:event_windowResize

    private void saveExecutableItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExecutableItemActionPerformed
        // Handle the save executable menu item
        
        gameOptions.confirmSettings();
        gameSettings.confirmSettings();
        gamePoints.confirmSettings();
        //gameDrivers.confirmSettings(); Not required, updated automatically.
        currentExecutable.saveData();        
        
    }//GEN-LAST:event_saveExecutableItemActionPerformed

    public void changePage(int pageNumber)
    {
        switch(pageNumber)
	{
            case 1: ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Executable Info"); break;
            case 2: ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Game Settings"); break;
            case 3: ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Game Options"); break;
            case 4: ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Points"); break;
            case 5: ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Drivers"); break;
            default: ((CardLayout)multiPageContainer.getLayout()).show(multiPageContainer, "Executable Info"); break;  
        }
    }
    
    private void closeExecutableItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeExecutableItemActionPerformed

        // Handle close executable menu event
        
        closeExecutable();      
        
    }//GEN-LAST:event_closeExecutableItemActionPerformed
    
    public void internalFrameClosing(InternalFrameEvent e) 
    {
        // Handle window closing event
        
        closeExecutable();
    }
    
    public void closeExecutable()
    {
        // Close the open executable window after user confirmation
        
        if (closingWindow == false)
        {
            int selectionOption = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this executable?", "Close Executable", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (selectionOption == JOptionPane.YES_OPTION)
            {
                try
                {
                    closingWindow = true;
                    this.setClosed(true);
                }
                catch (Exception errorReport)
                {
                    // This is a normal result of the closing of an internal window. Nothing should be done.
                }
            }       
        }
    }

    public void internalFrameClosed(InternalFrameEvent e) 
    {
    }

    public void internalFrameOpened(InternalFrameEvent e) 
    {
    }

    public void internalFrameIconified(InternalFrameEvent e) 
    {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) 
    {
    }

    public void internalFrameActivated(InternalFrameEvent e) 
    {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) 
    {
    }
    
    public void positionWindows()
    {
        // Re-position and resize internal windows based on size of main executable window
        
        int windowX = executableEditorWindow.getWidth();
        int windowY = executableEditorWindow.getHeight();
        if (windowX > 700)
        {
            windowX = 700;
        }
        if (windowY > 500)
        {
            windowY = 500;
        }
        executableEditorPane.setBounds(0,0,windowX,windowY);
        executableEditorPane.setDividerLocation(0.42);
        executableEditorPane.updateUI();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeExecutableItem;
    private javax.swing.JSplitPane executableEditorPane;
    private javax.swing.JDesktopPane executableEditorWindow;
    private javax.swing.JMenuBar executableMenuBar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem saveExecutableItem;
    // End of variables declaration//GEN-END:variables
    
}
