/*
 * ExecutableInfo.java
 *
 * Created on 01 January 2007, 01:32
 */

package chequeredflag.gui.panels;

/**
 *
 * @author  barrie
 */
public class ExecutableInfo extends javax.swing.JPanel {
    
    /** Creates new form ExecutableInfo */
    public ExecutableInfo(String gameVersion) 
    {
        initComponents();
        versionText.setText("Game Version: " + gameVersion);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        descText = new javax.swing.JLabel();
        versionText = new javax.swing.JLabel();
        leftAttention = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(3, 1));

        descText.setText("<html>Formula One Grand Prix / World Circuit Executable File</html>");
        add(descText);

        versionText.setText("<html>Game Version:</html>");
        add(versionText);

        leftAttention.setText("<html>Please use the tree menu on the left to select the editing facilities</html>");
        add(leftAttention);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descText;
    private javax.swing.JLabel leftAttention;
    private javax.swing.JLabel versionText;
    // End of variables declaration//GEN-END:variables
    
}
