/*
 * GameTweaks.java
 *
 * Created on 31 December 2006, 21:11
 */

package chequeredflag.gui.panels;

import chequeredflag.data.executable.GameMods;

/**
 *
 * @author  barrie
 */
public class GameTweaks extends javax.swing.JPanel 
{
    
    private GameMods gameTweaks;
    
    /**
     * Creates new form GameTweaks
     */
    public GameTweaks(GameMods passedGameTweaks) 
    {
        initComponents();
        gameTweaks = passedGameTweaks;
        fastFade.setSelected(gameTweaks.getFastFade());
        unlimitedTyres.setSelected(gameTweaks.getQualifyingTyres());
        removeLanguage.setSelected(gameTweaks.getLanguageSelection());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textPanel = new javax.swing.JPanel();
        descText = new javax.swing.JLabel();
        carsetText = new javax.swing.JLabel();
        booleanPanel = new javax.swing.JPanel();
        unlimitedTyres = new javax.swing.JCheckBox();
        fastFade = new javax.swing.JCheckBox();
        removeLanguage = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridLayout(3, 1));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        textPanel.setLayout(new java.awt.GridLayout(2, 1));

        descText.setText("<html>The following options can be modified to adjust the default behaviour of F1GP/WC.</html>");
        textPanel.add(descText);

        carsetText.setForeground(new java.awt.Color(0, 0, 0));
        carsetText.setText("<html>Please note that these options will not be loaded from, or saved to a carset</html>");
        textPanel.add(carsetText);

        add(textPanel);

        booleanPanel.setLayout(new java.awt.GridLayout(3, 1));

        unlimitedTyres.setText("Allow Unlimited Qualifying Tyres");
        unlimitedTyres.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        unlimitedTyres.setMargin(new java.awt.Insets(0, 0, 0, 0));
        booleanPanel.add(unlimitedTyres);

        fastFade.setText("Improve Menu Navigation Speed");
        fastFade.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        fastFade.setMargin(new java.awt.Insets(0, 0, 0, 0));
        booleanPanel.add(fastFade);

        removeLanguage.setText("Remove Language Selection Screen");
        removeLanguage.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        removeLanguage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        booleanPanel.add(removeLanguage);

        add(booleanPanel);

    }// </editor-fold>//GEN-END:initComponents
    
    public void confirmSettings()
    {
        
        // Confirms the values currently displayed on the interface. Updates the data values stored in memory.
        
        gameTweaks.setFastFade(fastFade.isSelected());
        gameTweaks.setQualifyingTyres(unlimitedTyres.isSelected());
        gameTweaks.setLanguageSelection(removeLanguage.isSelected());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booleanPanel;
    private javax.swing.JLabel carsetText;
    private javax.swing.JLabel descText;
    private javax.swing.JCheckBox fastFade;
    private javax.swing.JCheckBox removeLanguage;
    private javax.swing.JPanel textPanel;
    private javax.swing.JCheckBox unlimitedTyres;
    // End of variables declaration//GEN-END:variables
    
}
