/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * GameOptionsPanel.java
 *
 * Created on 31 December 2006, 21:11
 */

package chequeredflag.gui.executable.panels;

import chequeredflag.data.executable.GameOptions;

/**
 *
 * @author  barrie
 */
public class GameOptionsPanel extends javax.swing.JPanel 
{
    
    private GameOptions gameOptions;
    
    /**
     * Creates new form GameOptionsPanel
     */
    public GameOptionsPanel(GameOptions passedGameOptions) 
    {
        initComponents();
        gameOptions = passedGameOptions;
        fastFade.setSelected(gameOptions.getFastFade());
        removeLanguage.setSelected(gameOptions.getLanguageSelection());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textPanel = new javax.swing.JPanel();
        descText = new javax.swing.JLabel();
        carsetText = new javax.swing.JLabel();
        booleanPanel = new javax.swing.JPanel();
        fastFade = new javax.swing.JCheckBox();
        removeLanguage = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridLayout(3, 1));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        textPanel.setLayout(new java.awt.GridLayout(2, 1));

        descText.setText("<html>The following options can be modified to adjust the default behaviour of F1GP/WC.</html>");
        textPanel.add(descText);

        carsetText.setForeground(new java.awt.Color(0, 0, 0));
        carsetText.setText("<html>Please note that these options will not be loaded from, or saved to a carset</html>");
        textPanel.add(carsetText);

        add(textPanel);

        booleanPanel.setLayout(new java.awt.GridLayout(2, 1));

        fastFade.setText("Improve Menu Navigation Speed");
        fastFade.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        fastFade.setMargin(new java.awt.Insets(0, 0, 0, 0));
        booleanPanel.add(fastFade);

        removeLanguage.setText("Remove Language Selection Screen");
        removeLanguage.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        removeLanguage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        booleanPanel.add(removeLanguage);

        add(booleanPanel);

    }// </editor-fold>//GEN-END:initComponents
    
    public void confirmSettings()
    {
        
        // Confirms the values currently displayed on the interface. Updates the data values stored in memory.
        
        gameOptions.setFastFade(fastFade.isSelected());
        gameOptions.setLanguageSelection(removeLanguage.isSelected());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booleanPanel;
    private javax.swing.JLabel carsetText;
    private javax.swing.JLabel descText;
    private javax.swing.JCheckBox fastFade;
    private javax.swing.JCheckBox removeLanguage;
    private javax.swing.JPanel textPanel;
    // End of variables declaration//GEN-END:variables
    
}
