

/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * GameDriversPanel.java
 *
 * Created on 24 February 2007, 00:10
 */

package chequeredflag.gui.executable.panels;

import chequeredflag.data.executable.GameDrivers;

/**
 *
 * @author  barrie
 */
public class GameDriversPanel extends javax.swing.JPanel 
{
    
    private GameDrivers gameDrivers;
    private int[] driverSelectionHistory;
        
    /** Creates new form GameDriversPanel */
    public GameDriversPanel(GameDrivers passedGameDrivers) 
    {
        initComponents();
        driverSelectionHistory = new int[2];
        gameDrivers = passedGameDrivers;
        qualifyingGripField.setText(new Integer(gameDrivers.getQualifyingGrip(0)).toString());
        raceGripField.setText(new Integer(gameDrivers.getRaceGrip(0)).toString());
        driverList.setListData(gameDrivers.getAllDriverNames());
        driverList.setSelectedIndex(0);
        driverSelectionHistory[0] = 0;
        driverSelectionHistory[1] = 0;
        
    }
    
    public void updateFromCurrentValues(int driverIndex)
    {
        // Updates the program values stored in memory based on those displayed on the interface. 
        
        gameDrivers.setQualifyingGrip(driverIndex, new Integer(qualifyingGripField.getText()).intValue());
        gameDrivers.setRaceGrip(driverIndex, new Integer(raceGripField.getText()).intValue());
                        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        descText = new javax.swing.JLabel();
        driversPanel = new javax.swing.JPanel();
        driverScrollPane = new javax.swing.JScrollPane();
        driverList = new javax.swing.JList();
        attributesPanel = new javax.swing.JPanel();
        attributesLabelPanel = new javax.swing.JPanel();
        attributesDesc = new javax.swing.JLabel();
        attributesDataPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        qualifyingGripLabel = new javax.swing.JLabel();
        qualifyingGripField = new javax.swing.JTextField();
        raceGripLabel = new javax.swing.JLabel();
        raceGripField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        qualifyingGripMinus = new javax.swing.JButton();
        qualifyingGripPlus = new javax.swing.JButton();
        raceGripMinus = new javax.swing.JButton();
        raceGripPlus = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(0, 20));

        descText.setText("<html>The controls below allow the editing of both the names and attributes of all drivers. Please note that driver names can only be loaded and saved to a names file. It is not possible to directly change this information in the executable.</html>");
        add(descText, java.awt.BorderLayout.NORTH);

        driversPanel.setLayout(new java.awt.GridLayout(2, 1));

        driverList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        driverList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                driverListSelectionChange(evt);
            }
        });

        driverScrollPane.setViewportView(driverList);

        driversPanel.add(driverScrollPane);

        attributesPanel.setLayout(new java.awt.GridBagLayout());

        attributesDesc.setText("Driver Grip Levels");
        attributesLabelPanel.add(attributesDesc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 40.0;
        attributesPanel.add(attributesLabelPanel, gridBagConstraints);

        attributesDataPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        dataPanel.setLayout(new java.awt.GridLayout(2, 2));

        qualifyingGripLabel.setText("Qualifying");
        dataPanel.add(qualifyingGripLabel);

        qualifyingGripField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qualifyingGripField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qualifyingFieldChange(evt);
            }
        });

        dataPanel.add(qualifyingGripField);

        raceGripLabel.setText("Race");
        dataPanel.add(raceGripLabel);

        raceGripField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        raceGripField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                raceFieldChange(evt);
            }
        });

        dataPanel.add(raceGripField);

        attributesDataPanel.add(dataPanel);

        buttonPanel.setLayout(new java.awt.GridLayout(2, 2, 10, 0));

        qualifyingGripMinus.setText("-");
        qualifyingGripMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualifyingGripMinusActionPerformed(evt);
            }
        });

        buttonPanel.add(qualifyingGripMinus);

        qualifyingGripPlus.setText("+");
        qualifyingGripPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualifyingGripPlusActionPerformed(evt);
            }
        });

        buttonPanel.add(qualifyingGripPlus);

        raceGripMinus.setText("-");
        raceGripMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raceGripMinusActionPerformed(evt);
            }
        });

        buttonPanel.add(raceGripMinus);

        raceGripPlus.setText("+");
        raceGripPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raceGripPlusActionPerformed(evt);
            }
        });

        buttonPanel.add(raceGripPlus);

        attributesDataPanel.add(buttonPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 60.0;
        attributesPanel.add(attributesDataPanel, gridBagConstraints);

        driversPanel.add(attributesPanel);

        add(driversPanel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void qualifyingFieldChange(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qualifyingFieldChange

        int currentQualifyingGrip = new Integer(qualifyingGripField.getText()).intValue();
        qualifyingGripField.setText(new Integer(currentQualifyingGrip).toString());
        updateFromCurrentValues(driverSelectionHistory[0]);
                
    }//GEN-LAST:event_qualifyingFieldChange

    private void raceFieldChange(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_raceFieldChange

        int currentRaceGrip = new Integer(raceGripField.getText()).intValue();
        raceGripField.setText(new Integer(currentRaceGrip).toString());
        updateFromCurrentValues(driverSelectionHistory[0]);
                
    }//GEN-LAST:event_raceFieldChange

    private void raceGripPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raceGripPlusActionPerformed

        int currentRaceGrip = new Integer(raceGripField.getText()).intValue();
        if (currentRaceGrip < 255)
        {
            currentRaceGrip++;
            raceGripField.setText(new Integer(currentRaceGrip).toString());
            updateFromCurrentValues(driverSelectionHistory[0]);
        }
        
    }//GEN-LAST:event_raceGripPlusActionPerformed

    private void raceGripMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raceGripMinusActionPerformed

        int currentRaceGrip = new Integer(raceGripField.getText()).intValue();
        if (currentRaceGrip > 1)
        {
            currentRaceGrip--;
            raceGripField.setText(new Integer(currentRaceGrip).toString());
            updateFromCurrentValues(driverSelectionHistory[0]);
        }
        
    }//GEN-LAST:event_raceGripMinusActionPerformed

    private void qualifyingGripPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualifyingGripPlusActionPerformed

        int currentQualifyingGrip = new Integer(qualifyingGripField.getText()).intValue();
        if (currentQualifyingGrip < 255)
        {
            currentQualifyingGrip++;
            qualifyingGripField.setText(new Integer(currentQualifyingGrip).toString());
            updateFromCurrentValues(driverSelectionHistory[0]);
        }
        
    }//GEN-LAST:event_qualifyingGripPlusActionPerformed

    private void qualifyingGripMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualifyingGripMinusActionPerformed

        int currentQualifyingGrip = new Integer(qualifyingGripField.getText()).intValue();
        if (currentQualifyingGrip > 1)
        {
            currentQualifyingGrip--;
            qualifyingGripField.setText(new Integer(currentQualifyingGrip).toString());
            updateFromCurrentValues(driverSelectionHistory[0]);
        }
            
    }//GEN-LAST:event_qualifyingGripMinusActionPerformed

    private void driverListSelectionChange(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_driverListSelectionChange

        driverSelectionHistory[1] = driverSelectionHistory[0];
        driverSelectionHistory[0] = driverList.getSelectedIndex();
        updateFromCurrentValues(driverSelectionHistory[1]);
        qualifyingGripField.setText(new Integer(gameDrivers.getQualifyingGrip(driverList.getSelectedIndex())).toString());
        raceGripField.setText(new Integer(gameDrivers.getRaceGrip(driverList.getSelectedIndex())).toString());
        
    }//GEN-LAST:event_driverListSelectionChange
         
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attributesDataPanel;
    private javax.swing.JLabel attributesDesc;
    private javax.swing.JPanel attributesLabelPanel;
    private javax.swing.JPanel attributesPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel descText;
    private javax.swing.JList driverList;
    private javax.swing.JScrollPane driverScrollPane;
    private javax.swing.JPanel driversPanel;
    private javax.swing.JTextField qualifyingGripField;
    private javax.swing.JLabel qualifyingGripLabel;
    private javax.swing.JButton qualifyingGripMinus;
    private javax.swing.JButton qualifyingGripPlus;
    private javax.swing.JTextField raceGripField;
    private javax.swing.JLabel raceGripLabel;
    private javax.swing.JButton raceGripMinus;
    private javax.swing.JButton raceGripPlus;
    // End of variables declaration//GEN-END:variables
    
}
