/*
 * GameTeamsPanel.java
 *
 * Created on 06 October 2007, 19:17
 */

package chequeredflag.gui.executable.panels;

import chequeredflag.data.executable.GameTeams;

/**
 *
 * @author  barrie
 */
public class GameTeamsPanel extends javax.swing.JPanel {
    
    private GameTeams gameTeams;
    private int[] teamSelectionHistory;
    
    /** Creates new form GameTeamsPanel */
    public GameTeamsPanel(GameTeams passedGameTeams) 
    {
        initComponents();
        teamSelectionHistory = new int[2];
        gameTeams = passedGameTeams;
        bhpSettingField.setText(new Integer(gameTeams.getBHPSetting(0)).toString());
        teamList.setListData(gameTeams.getAllTeamNames());
        teamList.setSelectedIndex(0);
        teamSelectionHistory[0] = 0;
        teamSelectionHistory[1] = 0;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        descText = new javax.swing.JLabel();
        teamsPanel = new javax.swing.JPanel();
        teamScrollPane = new javax.swing.JScrollPane();
        teamList = new javax.swing.JList();
        namePanel = new javax.swing.JPanel();
        nameDataPanel = new javax.swing.JPanel();
        teamNameLabel = new javax.swing.JLabel();
        teamNameField = new javax.swing.JTextField();
        teamChangeButton = new javax.swing.JButton();
        engineDataPanel = new javax.swing.JPanel();
        engineNameLabel = new javax.swing.JLabel();
        engineNameField = new javax.swing.JTextField();
        engineChangeButton = new javax.swing.JButton();
        bhpDataPanel = new javax.swing.JPanel();
        bhpSettingLabel = new javax.swing.JLabel();
        bhpSettingField = new javax.swing.JTextField();
        bhpChangePanel = new javax.swing.JPanel();
        bhpSettingMinus = new javax.swing.JButton();
        bhpSettingPlus = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        descText.setText("<html>The controls below allow the editing of both the names and attributes of all teams.</html>");
        add(descText, java.awt.BorderLayout.NORTH);

        teamsPanel.setLayout(new java.awt.GridLayout(2, 1));

        teamList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        teamList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                teamListSelectionChange(evt);
            }
        });

        teamScrollPane.setViewportView(teamList);

        teamsPanel.add(teamScrollPane);

        namePanel.setLayout(new java.awt.GridLayout(3, 3));

        nameDataPanel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        teamNameLabel.setText("Team Name");
        nameDataPanel.add(teamNameLabel);

        nameDataPanel.add(teamNameField);

        teamChangeButton.setText("Change Name");
        teamChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamChangeButtonActionPerformed(evt);
            }
        });

        nameDataPanel.add(teamChangeButton);

        namePanel.add(nameDataPanel);

        engineDataPanel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        engineNameLabel.setText("Engine Supplier");
        engineDataPanel.add(engineNameLabel);

        engineDataPanel.add(engineNameField);

        engineChangeButton.setText("Change Name");
        engineChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineChangeButtonActionPerformed(evt);
            }
        });

        engineDataPanel.add(engineChangeButton);

        namePanel.add(engineDataPanel);

        bhpDataPanel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        bhpSettingLabel.setText("BHP");
        bhpDataPanel.add(bhpSettingLabel);

        bhpDataPanel.add(bhpSettingField);

        bhpChangePanel.setLayout(new java.awt.GridLayout(1, 2));

        bhpSettingMinus.setText("-");
        bhpSettingMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhpSettingMinusActionPerformed(evt);
            }
        });

        bhpChangePanel.add(bhpSettingMinus);

        bhpSettingPlus.setText("+");
        bhpSettingPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhpSettingPlusActionPerformed(evt);
            }
        });

        bhpChangePanel.add(bhpSettingPlus);

        bhpDataPanel.add(bhpChangePanel);

        namePanel.add(bhpDataPanel);

        teamsPanel.add(namePanel);

        add(teamsPanel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void bhpSettingPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhpSettingPlusActionPerformed

        int currentBHPSetting = new Integer(bhpSettingField.getText()).intValue();
        if (currentBHPSetting < 1300) // Not the maximal limit possible, but the one used by F1ED
        {
            currentBHPSetting++;
            bhpSettingField.setText(new Integer(currentBHPSetting).toString());
            updateFromCurrentValues(teamSelectionHistory[0]);
        }
        
    }//GEN-LAST:event_bhpSettingPlusActionPerformed

    private void bhpSettingMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhpSettingMinusActionPerformed

        int currentBHPSetting = new Integer(bhpSettingField.getText()).intValue();
        if (currentBHPSetting > 0)
        {
            currentBHPSetting++;
            bhpSettingField.setText(new Integer(currentBHPSetting).toString());
            updateFromCurrentValues(teamSelectionHistory[0]);
        }
        
    }//GEN-LAST:event_bhpSettingMinusActionPerformed

    private void engineChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineChangeButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_engineChangeButtonActionPerformed

    private void teamChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamChangeButtonActionPerformed
// Handles the event for the change name button
        
        gameTeams.setTeamName(teamSelectionHistory[0], teamNameField.getText());
        teamList.revalidate();
        teamList.repaint();
    }//GEN-LAST:event_teamChangeButtonActionPerformed

    public void updateFromCurrentValues(int teamIndex)
    {
        // Updates the program values stored in memory based on those displayed on the interface. 
        
        gameTeams.setBHPSetting(teamIndex, new Integer(bhpSettingField.getText()).intValue());
                                
    }
    
    private void teamListSelectionChange(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_teamListSelectionChange
        teamSelectionHistory[1] = teamSelectionHistory[0];
        teamSelectionHistory[0] = teamList.getSelectedIndex();
        updateFromCurrentValues(teamSelectionHistory[1]);
        bhpSettingField.setText(new Integer(gameTeams.getBHPSetting(teamList.getSelectedIndex())).toString());
        teamNameField.setText(gameTeams.getTeamName(teamList.getSelectedIndex()));
        engineNameField.setText(gameTeams.getEngineName(teamList.getSelectedIndex()));
    }//GEN-LAST:event_teamListSelectionChange
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bhpChangePanel;
    private javax.swing.JPanel bhpDataPanel;
    private javax.swing.JTextField bhpSettingField;
    private javax.swing.JLabel bhpSettingLabel;
    private javax.swing.JButton bhpSettingMinus;
    private javax.swing.JButton bhpSettingPlus;
    private javax.swing.JLabel descText;
    private javax.swing.JButton engineChangeButton;
    private javax.swing.JPanel engineDataPanel;
    private javax.swing.JTextField engineNameField;
    private javax.swing.JLabel engineNameLabel;
    private javax.swing.JPanel nameDataPanel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JButton teamChangeButton;
    private javax.swing.JList teamList;
    private javax.swing.JTextField teamNameField;
    private javax.swing.JLabel teamNameLabel;
    private javax.swing.JScrollPane teamScrollPane;
    private javax.swing.JPanel teamsPanel;
    // End of variables declaration//GEN-END:variables
    
}
