/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * GameSettingsPanel.java
 *
 * Created on 11 February 2007, 21:11
 */

package chequeredflag.gui.executable.panels;

import chequeredflag.data.executable.GameSettings;

/**
 *
 * @author  barrie
 */
public class GameSettingsPanel extends javax.swing.JPanel 
{
    
    private GameSettings gameSettings;
    
    /**
     * Creates new form GameOptionsPanel
     */
    public GameSettingsPanel(GameSettings passedGameSettings) 
    {
        initComponents();
        gameSettings = passedGameSettings;
        unlimitedTyres.setSelected(gameSettings.getQualifyingTyres());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        textPanel = new javax.swing.JPanel();
        descText = new javax.swing.JLabel();
        booleanPanel = new javax.swing.JPanel();
        unlimitedTyres = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridLayout(3, 1));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        textPanel.setLayout(new java.awt.GridLayout(1, 1));

        descText.setText("<html>The following options can be modified to adjust the default behaviour of F1GP/WC.</html>");
        textPanel.add(descText);

        add(textPanel);

        booleanPanel.setLayout(new java.awt.GridLayout(1, 1));

        unlimitedTyres.setText("Allow Unlimited Qualifying Tyres");
        unlimitedTyres.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        unlimitedTyres.setMargin(new java.awt.Insets(0, 0, 0, 0));
        booleanPanel.add(unlimitedTyres);

        add(booleanPanel);

    }// </editor-fold>//GEN-END:initComponents
    
    public void confirmSettings()
    {
        
        // Confirms the values currently displayed on the interface. Updates the data values stored in memory.
        
        gameSettings.setQualifyingTyres(unlimitedTyres.isSelected());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booleanPanel;
    private javax.swing.JLabel descText;
    private javax.swing.JPanel textPanel;
    private javax.swing.JCheckBox unlimitedTyres;
    // End of variables declaration//GEN-END:variables
    
}
