
/*
 * Chequered Flag: An editor for Formula One Grand Prix/World Circuit
 * Copyright (C) 2005-2007  The Chequered Flag Development Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

/*
 * GamePointsPanel.java
 *
 * Created on 11 February 2007, 18:03
 */

package chequeredflag.gui.executable.panels;

import chequeredflag.data.executable.GamePoints;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author  barrie
 */
public class GamePointsPanel extends javax.swing.JPanel 
{
    
    private GamePoints gamePoints;
    private JTextField[] pointsField;
        
    /**
     * Creates new form GamePointsPanel
     */
    public GamePointsPanel(GamePoints passedGamePoints, int gameVersion) 
    {
        initComponents();
        gamePoints = passedGamePoints;
        JLabel[] pointsLabel = new JLabel[26];
        for (int x=0;x<26;x++)
        {
            if ((x == 0) || (x == 20))
            {
                pointsLabel[x] = new JLabel(x+1 + "st");
            }
            else
            {
                if (( x == 1) || (x == 21))
                {
                    pointsLabel[x] = new JLabel(x+1 + "nd");
                }
                else
                {
                    if (( x == 2) || (x == 22))
                    {
                        pointsLabel[x] = new JLabel(x+1 + "rd");
                    }
                    else
                    {
                        pointsLabel[x] = new JLabel(x+1 + "th");
                    }
                }
            }
        }
        pointsField = new JTextField[26];
        for (int x=0;x<26;x++)
        {
            pointsField[x] = new JTextField("");
        }
        JPanel firstPagePanel = new JPanel();
        JPanel secondPagePanel = new JPanel();
        JPanel thirdPagePanel = new JPanel();
        firstPagePanel.setLayout(new GridLayout(9,2,0,0));
        secondPagePanel.setLayout(new GridLayout(9,2,0,0));
        thirdPagePanel.setLayout(new GridLayout(9,2,0,0));
        for (int x=0;x<9;x++)
        {
            firstPagePanel.add(pointsLabel[x]);
            firstPagePanel.add(pointsField[x]);
        }
        for (int x=9;x<18;x++)
        {
            secondPagePanel.add(pointsLabel[x]);
            secondPagePanel.add(pointsField[x]);
        }
        for (int x=18;x<26;x++)
        {
            thirdPagePanel.add(pointsLabel[x]);
            thirdPagePanel.add(pointsField[x]);
        }
        pointsPanel.add("First Page", firstPagePanel);
        pointsPanel.add("Second Page", secondPagePanel);
        pointsPanel.add("Third Page", thirdPagePanel);
        ((CardLayout)pointsPanel.getLayout()).show(pointsPanel, "First Page");
        for (int x=0;x<26;x++)
        {
            pointsField[x].setText(new String(new Integer(gamePoints.getPointValue(x)).toString()));
        }
        //unlimitedTyres.setSelected(gameSettings.getQualifyingTyres());
    }
    
    public void changePointsPage(int pageNumber)
    {
        switch(pageNumber)
	{
            case 1: ((CardLayout)pointsPanel.getLayout()).show(pointsPanel, "First Page"); break;
            case 2: ((CardLayout)pointsPanel.getLayout()).show(pointsPanel, "Second Page"); break;
            case 3: ((CardLayout)pointsPanel.getLayout()).show(pointsPanel, "Third Page"); break;
            default: ((CardLayout)pointsPanel.getLayout()).show(pointsPanel, "First Page"); break;
        }
    }
    
    public void confirmSettings()
    {
        
        // Confirms the values currently displayed on the interface. Updates the data values stored in memory.
        
        for (int x=0;x<26;x++)
        {
            gamePoints.setPointValue(x, new Integer(pointsField[x].getText()).intValue());
        }
                
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        displayPanel = new javax.swing.JPanel();
        descPanel = new javax.swing.JPanel();
        descText = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        firstPageButton = new javax.swing.JButton();
        secondPageButton = new javax.swing.JButton();
        thirdPageButton = new javax.swing.JButton();
        pointsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout(10, 10));

        displayPanel.setLayout(new java.awt.GridBagLayout());

        descPanel.setLayout(new java.awt.GridLayout(1, 1));

        descText.setText("<html>The following options allow the points awarded to cars after a race to be modified. Please note that an unpacked version of F1GP/WC is required to be able to edit all the available positions. Only the first six places can be adjusted in the packed version.</html>");
        descPanel.add(descText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        displayPanel.add(descPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 3, 30, 0));

        firstPageButton.setText("Page 1");
        firstPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstPageButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(firstPageButton);

        secondPageButton.setText("Page 2");
        secondPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondPageButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(secondPageButton);

        thirdPageButton.setText("Page 3");
        thirdPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdPageButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(thirdPageButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        displayPanel.add(buttonPanel, gridBagConstraints);

        add(displayPanel, java.awt.BorderLayout.NORTH);

        pointsPanel.setLayout(new java.awt.CardLayout());

        add(pointsPanel, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void thirdPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdPageButtonActionPerformed

        changePointsPage(3);
        
    }//GEN-LAST:event_thirdPageButtonActionPerformed

    private void secondPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondPageButtonActionPerformed

        changePointsPage(2);
        
    }//GEN-LAST:event_secondPageButtonActionPerformed

    private void firstPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstPageButtonActionPerformed

        changePointsPage(1);
        
    }//GEN-LAST:event_firstPageButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel descPanel;
    private javax.swing.JLabel descText;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton firstPageButton;
    private javax.swing.JPanel pointsPanel;
    private javax.swing.JButton secondPageButton;
    private javax.swing.JButton thirdPageButton;
    // End of variables declaration//GEN-END:variables
    
}
